In [33]:
import pandas as pd

In [34]:
pd.read_csv("C:/Users/wecep/Objectel/ListTest.csv", index_col="Group Name",low_memory=False)

,Tier,RecordID,ProviderEntityID,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,Provider Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
Group Name,,,,,,,,,,,,,,,,,,,,,
Align Networks,-1,84142,125861,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,270276119,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
Align Networks,-1,103764,129343,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
Align Networks,-1,106784,136107,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
Align Networks,-1,122878,167566,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,270276119,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
Align Networks,-1,131499,184425,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,270276119,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Align Networks,20,79405,178810,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Mabel,NaN,Cobos,10661715.0,270276119,...,30348-5159,8663890211,9049980299,1.356363e+09,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com
Align Networks,20,79405,178810,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,Perry,10661715.0,270276119,...,30348-5159,8663890211,9049980299,1.356363e+09,2022/01/01,1356363360,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com
Align Networks,20,78870,181692,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",Referrals@AlignNetworks.com,NaN,NaN,NaN,954456330.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,NaN,Y,Y,kathy.drkatz@gmail.com
Align Networks,21,20213,65334,Andy Truongvinh dba Andy Truongvinh Chiropractic,Referrals@AlignNetworks.com,DR,NaN,ANDY TRUONGVINH,10619354.0,270276119,...,30348-5159,8663890211,9049980299,1.043319e+09,2022/01/01,1043318645,1.043319e+08,Y,Y,drandydc@gmail.com
Align Networks,21,79405,149192,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,R. Perry,10661715.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com

In [4]:
pd.read_csv("C:/Users/wecep/Objectel/ListTest.csv", low_memory=False)

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
3,-1,122878,167566,Align Networks,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
4,-1,131499,184425,Align Networks,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25705,20,79405,178810,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Mabel,NaN,Cobos,10661715.0,...,30348-5159,8663890211,9049980299,1.356363e+09,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com
25706,20,79405,178810,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,Perry,10661715.0,...,30348-5159,8663890211,9049980299,1.356363e+09,2022/01/01,1356363360,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com
25707,20,78870,181692,Align Networks,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",Referrals@AlignNetworks.com,NaN,NaN,NaN,954456330.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,NaN,Y,Y,kathy.drkatz@gmail.com
25708,21,20213,65334,Align Networks,Andy Truongvinh dba Andy Truongvinh Chiropractic,Referrals@AlignNetworks.com,DR,NaN,ANDY TRUONGVINH,10619354.0,...,30348-5159,8663890211,9049980299,1.043319e+09,2022/01/01,1043318645,1.043319e+08,Y,Y,drandydc@gmail.com
25709,21,79405,149192,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,R. Perry,10661715.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com

In [5]:
align = pd.read_csv("C:/Users/wecep/Objectel/ListTest.csv", low_memory=False)

In [6]:
align = pd.read_csv("C:/Users/wecep/Objectel/ListTest.csv", squeeze=True,low_memory=False)

In [8]:
align.head(5)

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
3,-1,122878,167566,Align Networks,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
4,-1,131499,184425,Align Networks,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com

In [15]:
align.tail()

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
25705,20,79405,178810,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Mabel,NaN,Cobos,10661715.0,...,30348-5159,8663890211,9049980299,1.356363e+09,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com
25706,20,79405,178810,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,Perry,10661715.0,...,30348-5159,8663890211,9049980299,1.356363e+09,2022/01/01,1356363360,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com
25707,20,78870,181692,Align Networks,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",Referrals@AlignNetworks.com,NaN,NaN,NaN,954456330.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,NaN,Y,Y,kathy.drkatz@gmail.com
25708,21,20213,65334,Align Networks,Andy Truongvinh dba Andy Truongvinh Chiropractic,Referrals@AlignNetworks.com,DR,NaN,ANDY TRUONGVINH,10619354.0,...,30348-5159,8663890211,9049980299,1.043319e+09,2022/01/01,1043318645,1.043319e+08,Y,Y,drandydc@gmail.com
25709,21,79405,149192,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,R. Perry,10661715.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com

In [9]:
align.sort_values(by="Tier")

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
3,-1,122878,167566,Align Networks,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
4,-1,131499,184425,Align Networks,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25676,20,102231,126247,Align Networks,Advanced Acupuncture Inc,Referrals@AlignNetworks.com,Cathryn,NaN,Yun-Qiu Hu,954459823.0,...,30348-5159,8663890211,9049980299,1.710993e+09,2022/01/01,1093868622,1.710993e+09,Y,Y,advanced_acupuncture@yahoo.com
25677,20,102422,126560,Align Networks,United Alternative Medical Group Inc dba T.Y. ...,Referrals@AlignNetworks.com,Min,NaN,Choi,455244350.0,...,30348-5159,8663890211,9049980299,1.225358e+09,2022/01/01,1225357965,1.225358e+08,Y,Y,tywellness@gmail.com
25665,20,89929,114593,Align Networks,Chau AI Au dba Aus Acupuncture & Herb Clinic,Referrals@AlignNetworks.com,CHAU,NaN,AI AU,548914423.0,...,30348-5159,8663890211,9049980299,1.740215e+09,2022/01/01,1740214717,1.740215e+09,Y,Y,chauaiau@yahoo.com
25708,21,20213,65334,Align Networks,Andy Truongvinh dba Andy Truongvinh Chiropractic,Referrals@AlignNetworks.com,DR,NaN,ANDY TRUONGVINH,10619354.0,...,30348-5159,8663890211,9049980299,1.043319e+09,2022/01/01,1043318645,1.043319e+08,Y,Y,drandydc@gmail.com
25709,21,79405,149192,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,R. Perry,10661715.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com

In [10]:
align.sort_values(by="Tier",inplace = True)

In [11]:
align.head()

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
3,-1,122878,167566,Align Networks,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
4,-1,131499,184425,Align Networks,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com

In [12]:
align.value_counts()
align.value_counts(ascending = False)

Series([], dtype: int64)

In [13]:
align.head()

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
3,-1,122878,167566,Align Networks,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
4,-1,131499,184425,Align Networks,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com

In [14]:
align = pd.read_csv("C://Users/wecep/Objectel/ListTest.csv", squeeze=True,low_memory=False, index_col="Group Name")

In [15]:
align.value_counts()
align.value_counts(ascending = False)

Series([], dtype: int64)

In [16]:
align.value_counts("Group Name")

Group Name
Align Networks    25710
dtype: int64

In [17]:
align.value_counts("ProviderFirstName")

ProviderFirstName
Michael        290
Christopher    278
Matthew        256
Andrew         247
Jennifer       237
              ...
KARLO            1
Jyoti            1
Jushua           1
Juntae           1
yanzhong         1
Length: 2796, dtype: int64

In [18]:
align.value_counts("ProviderLastName")

ProviderLastName
Lee           225
Schwartz      151
Chen          140
King          134
Amato         133
             ...
J MORTON        1
J Mangan        1
J McMillin      1
J Medina        1
zhu             1
Length: 6245, dtype: int64

In [19]:
align.value_counts("Facility Tax ID")

Facility Tax ID
815145975.0    4482
825160608.0    2850
330912929.0    2521
330493339.0     850
912073074.0     775
               ...
612372892.0       1
613054161.0       1
613650947.0       1
614205792.0       1
954888108.0       1
Length: 1787, dtype: int64

In [20]:
align.value_counts("Provider Tax ID")

Provider Tax ID
270276119    25710
dtype: int64

In [21]:
align.value_counts("PhysicalTherapistNPI")

PhysicalTherapistNPI
              2937
1689215956     134
1659740942     134
1861554693     132
1124547260     131
              ...
1548554397       1
1548574379       1
1548579154       1
1164624599       1
954814783        1
Length: 5443, dtype: int64

In [22]:
align.value_counts("ServiceFacilityNPI")

ServiceFacilityNPI
1.952395e+09    1893
1.952395e+08     628
1.841268e+08     621
1.770830e+09     550
1.811911e+08     504
                ...
1.104816e+09       1
1.104377e+09       1
1.104291e+09       1
1.104131e+09       1
6.194603e+09       1
Length: 1945, dtype: int64

In [23]:
align.columns

Index(['Tier', 'RecordID', 'ProviderEntityID', 'Facility Name',
       'ProviderEmail', 'ProviderFirstName', 'ProviderMiddleName',
       'ProviderLastName', 'Facility Tax ID', 'Provider Tax ID', 'Degree',
       'License', 'PrimarySpecialty', 'PracticeStreet1', 'PracticeStreet2',
       'PracticeCity', 'State', 'PracticeZip', 'FacilityPhone',
       'PracticePhone', 'Fax', 'BillingAddress1', 'BillingAddress2',
       'BillingCity', 'BillingState', 'BillingZip', 'BillingPhone',
       'BillingFax', 'PLgroupNPI', 'SB863ConfirmationDate',
       'PhysicalTherapistNPI', 'ServiceFacilityNPI', 'ReferralOnly',
       'AcceptingWCPatients', 'RenderingProviderEmail'],
      dtype='object')

In [24]:
align.value_counts("BillingState")

BillingState
GA    25710
dtype: int64

In [25]:
align.value_counts("State")

State
CA    25710
dtype: int64

In [26]:
align.value_counts("Facility Name")

Facility Name
New Life Physical Therapy Services PC dba New Life Rehabilitation                                     4478
CALIFORNIA LUNA CARE PHYSICAL THERAPY PC-Mobile PT                                                    2826
MDRS Spine & Sport, Inc                                                                               2454
San Luis Physical Therapy and Orthopedic Rehabilitation Inc dba Movement for Life Physical Therapy     574
Vargo Physical Therapy, Inc                                                                            523
                                                                                                      ...
Ed Green dba Ed Green Chiropractic                                                                       1
Eckerson Chiropractic                                                                                    1
New Light Physical Therapy and Wellness Center                                                           1
Eastao Corp. dba Holistic Healing Source                                                                 1
Zylna Granado                                                                                            1
Length: 1942, dtype: int64

In [27]:
align.value_counts("BillingZip")

BillingZip
30348-5159    25710
dtype: int64

In [28]:
align.value_counts("PrimarySpecialty", ascending = True)

PrimarySpecialty
Could be All                 5
Massage Therapy             29
Acupuncture                916
Chiropractic Services      987
Physical Therapy         23773
dtype: int64

In [29]:
align.value_counts("State")

State
CA    25710
dtype: int64

In [30]:
align.value_counts("PrimarySpecialty",normalize = True) * 100

PrimarySpecialty
Physical Therapy         92.465967
Chiropractic Services     3.838973
Acupuncture               3.562816
Massage Therapy           0.112797
Could be All              0.019448
dtype: float64

In [31]:
align.nunique()

Tier                        13
RecordID                  1768
ProviderEntityID          3085
Facility Name             1942
ProviderEmail                1
ProviderFirstName         2796
ProviderMiddleName           0
ProviderLastName          6245
Facility Tax ID           1787
Provider Tax ID              1
Degree                       0
License                   7129
PrimarySpecialty             5
PracticeStreet1           3042
PracticeStreet2              0
PracticeCity               657
State                        1
PracticeZip                829
FacilityPhone             2450
PracticePhone                1
Fax                          1
BillingAddress1              1
BillingAddress2              0
BillingCity                  1
BillingState                 1
BillingZip                   1
BillingPhone                 1
BillingFax                   1
PLgroupNPI                1751
SB863ConfirmationDate        1
PhysicalTherapistNPI      5443
ServiceFacilityNPI        1945
ReferralOnly                 1
AcceptingWCPatients          1
RenderingProviderEmail    1603
dtype: int64

In [63]:
align.nunique()

Tier                        13
RecordID                  1768
ProviderEntityID          3085
Group Name                   1
Facility Name             1942
ProviderEmail                1
ProviderFirstName         2796
ProviderMiddleName           0
ProviderLastName          6245
Facility Tax ID           1787
Provider Tax ID              1
Degree                       0
License                   7129
PrimarySpecialty             5
PracticeStreet1           3042
PracticeStreet2              0
PracticeCity               657
State                        1
PracticeZip                829
FacilityPhone             2450
PracticePhone                1
Fax                          1
BillingAddress1              1
BillingAddress2              0
BillingCity                  1
BillingState                 1
BillingZip                   1
BillingPhone                 1
BillingFax                   1
PLgroupNPI                1751
SB863ConfirmationDate        1
PhysicalTherapistNPI      5443
ServiceFacilityNPI        1945
ReferralOnly                 1
AcceptingWCPatients          1
RenderingProviderEmail    1603
dtype: int64

In [64]:
align.drop_duplicates()

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
3,-1,122878,167566,Align Networks,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
4,-1,131499,184425,Align Networks,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25705,20,79405,178810,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Mabel,NaN,Cobos,10661715.0,...,30348-5159,8663890211,9049980299,1.356363e+09,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com
25706,20,79405,178810,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,Perry,10661715.0,...,30348-5159,8663890211,9049980299,1.356363e+09,2022/01/01,1356363360,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com
25707,20,78870,181692,Align Networks,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",Referrals@AlignNetworks.com,NaN,NaN,NaN,954456330.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,NaN,Y,Y,kathy.drkatz@gmail.com
25708,21,20213,65334,Align Networks,Andy Truongvinh dba Andy Truongvinh Chiropractic,Referrals@AlignNetworks.com,DR,NaN,ANDY TRUONGVINH,10619354.0,...,30348-5159,8663890211,9049980299,1.043319e+09,2022/01/01,1043318645,1.043319e+08,Y,Y,drandydc@gmail.com
25709,21,79405,149192,Align Networks,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,R. Perry,10661715.0,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com

In [32]:
align.head()

,Tier,RecordID,ProviderEntityID,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,Provider Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
Group Name,,,,,,,,,,,,,,,,,,,,,
Align Networks,-1,84142,125861,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,270276119,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
Align Networks,-1,103764,129343,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
Align Networks,-1,106784,136107,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
Align Networks,-1,122878,167566,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,270276119,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
Align Networks,-1,131499,184425,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,270276119,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com

In [33]:
align.iloc[100]

Tier                                                        0
RecordID                                                 1567
ProviderEntityID                                        46698
Facility Name                       Concentra Medical Centers
ProviderEmail                     Referrals@AlignNetworks.com
ProviderFirstName                                     Michael
ProviderMiddleName                                        NaN
ProviderLastName                                       Coller
Facility Tax ID                                   770469725.0
Provider Tax ID                                     270276119
Degree                                                    NaN
License                                               DC22410
PrimarySpecialty                             Physical Therapy
PracticeStreet1                          1675 Alhambra Blvd B
PracticeStreet2                                           NaN
PracticeCity                                       Sacramento
State                                                      CA
PracticeZip                                             95816
FacilityPhone                                      9164514580
PracticePhone                                      8663890211
Fax                                                9049980299
BillingAddress1                               P.O. Box 105159
BillingAddress2                                           NaN
BillingCity                                           Atlanta
BillingState                                               GA
BillingZip                                         30348-5159
BillingPhone                                       8663890211
BillingFax                                         9049980299
PLgroupNPI                                       1861969024.0
SB863ConfirmationDate                              2022/01/01
PhysicalTherapistNPI                               1497994362
ServiceFacilityNPI                                131692733.0
ReferralOnly                                                Y
AcceptingWCPatients                                         Y
RenderingProviderEmail    customersupport_align@concentra.com
Name: Align Networks, dtype: object

In [34]:
align.iloc[[0, 3, 5, 10]]

,Tier,RecordID,ProviderEntityID,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,Provider Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
Group Name,,,,,,,,,,,,,,,,,,,,,
Align Networks,-1,84142,125861,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,270276119,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
Align Networks,-1,122878,167566,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,270276119,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
Align Networks,0,1567,5282,Concentra Medical Centers,Referrals@AlignNetworks.com,NaN,NaN,NaN,770469725.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.316927e+08,Y,Y,customersupport_align@concentra.com
Align Networks,0,1567,5282,Concentra Medical Centers,Referrals@AlignNetworks.com,Sapna,NaN,awale,770469725.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1326386764,1.316927e+08,Y,Y,customersupport_align@concentra.com

In [35]:
align.iloc[-3:]

,Tier,RecordID,ProviderEntityID,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,Provider Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
Group Name,,,,,,,,,,,,,,,,,,,,,
Align Networks,20,78870,181692,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",Referrals@AlignNetworks.com,NaN,NaN,NaN,954456330.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,NaN,Y,Y,kathy.drkatz@gmail.com
Align Networks,21,20213,65334,Andy Truongvinh dba Andy Truongvinh Chiropractic,Referrals@AlignNetworks.com,DR,NaN,ANDY TRUONGVINH,10619354.0,270276119,...,30348-5159,8663890211,9049980299,1.043319e+09,2022/01/01,1043318645,1.043319e+08,Y,Y,drandydc@gmail.com
Align Networks,21,79405,149192,Advanced Dynamics Physical Therapy DBA Matthew...,Referrals@AlignNetworks.com,Matthew,NaN,R. Perry,10661715.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.356363e+09,Y,Y,Advanceddynamic@yahoo.com

In [38]:
align.iloc[:3]

,Tier,RecordID,ProviderEntityID,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,Provider Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
Group Name,,,,,,,,,,,,,,,,,,,,,
Align Networks,-1,84142,125861,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,270276119,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
Align Networks,-1,103764,129343,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
Align Networks,-1,106784,136107,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net

In [40]:
align.loc[2]

KeyError: 2

In [41]:
align = pd.read_csv("C:/Users/wecep/Objectel/ListTest.csv",low_memory=False, parse_dates=["SB863ConfirmationDate"])

In [42]:
align.head(3)

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022-01-01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022-01-01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022-01-01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net

In [43]:
align.shape

(25710, 36)

In [44]:
align.size

925560

In [46]:
align.head(3)

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022-01-01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022-01-01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022-01-01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net

In [49]:
align.dtypes

Tier                               int64
RecordID                           int64
ProviderEntityID                   int64
Group Name                        object
Facility Name                     object
ProviderEmail                     object
ProviderFirstName                 object
ProviderMiddleName               float64
ProviderLastName                  object
Facility Tax ID                  float64
Provider Tax ID                    int64
Degree                           float64
License                           object
PrimarySpecialty                  object
PracticeStreet1                   object
PracticeStreet2                  float64
PracticeCity                      object
State                             object
PracticeZip                        int64
FacilityPhone                      int64
PracticePhone                      int64
Fax                                int64
BillingAddress1                   object
BillingAddress2                  float64
BillingCity                       object
BillingState                      object
BillingZip                        object
BillingPhone                       int64
BillingFax                         int64
PLgroupNPI                       float64
SB863ConfirmationDate     datetime64[ns]
PhysicalTherapistNPI              object
ServiceFacilityNPI               float64
ReferralOnly                      object
AcceptingWCPatients               object
RenderingProviderEmail            object
dtype: object

In [50]:
align.nunique()

Tier                        13
RecordID                  1768
ProviderEntityID          3085
Group Name                   1
Facility Name             1942
ProviderEmail                1
ProviderFirstName         2796
ProviderMiddleName           0
ProviderLastName          6245
Facility Tax ID           1787
Provider Tax ID              1
Degree                       0
License                   7129
PrimarySpecialty             5
PracticeStreet1           3042
PracticeStreet2              0
PracticeCity               657
State                        1
PracticeZip                829
FacilityPhone             2450
PracticePhone                1
Fax                          1
BillingAddress1              1
BillingAddress2              0
BillingCity                  1
BillingState                 1
BillingZip                   1
BillingPhone                 1
BillingFax                   1
PLgroupNPI                1751
SB863ConfirmationDate        1
PhysicalTherapistNPI      5443
ServiceFacilityNPI        1945
ReferralOnly                 1
AcceptingWCPatients          1
RenderingProviderEmail    1603
dtype: int64

In [86]:
align.sample(3)

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
16173,3,131429,185236,Align Networks,CALIFORNIA LUNA CARE PHYSICAL THERAPY PC-Mobil...,Referrals@AlignNetworks.com,Joshua,NaN,Schwartz,825160608.0,...,30348-5159,8663890211,9049980299,1.689162e+09,2022-01-01,1659740942,NaN,Y,Y,onecall@getluna.com
21037,4,11182,146641,Align Networks,"MDRS Spine & Sport, Inc",Referrals@AlignNetworks.com,Kevin,NaN,Saldana,330912929.0,...,30348-5159,8663890211,9049980299,1.952395e+09,2022-01-01,1346546835,1.952395e+09,Y,Y,NaN
12686,3,14570,64229,Align Networks,"West Star Physical Therapy, Inc",Referrals@AlignNetworks.com,John,NaN,Paul Rivera,330574098.0,...,30348-5159,8663890211,9049980299,1.376765e+09,2022-01-01,1427279629,1.376765e+09,Y,Y,sandrab@atmi.net

In [51]:
align.max()

C:\Users\wecep\AppData\Local\Temp/ipykernel_3364/1287763311.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  align.max()

Tier                                              21
RecordID                                      132271
ProviderEntityID                              187716
Group Name                            Align Networks
Facility Name                          Zylna Granado
ProviderEmail            Referrals@AlignNetworks.com
ProviderMiddleName                               NaN
Facility Tax ID                          954888108.0
Provider Tax ID                            270276119
Degree                                           NaN
PrimarySpecialty                    Physical Therapy
PracticeStreet1          Virtual Physical Therapists
PracticeStreet2                                  NaN
PracticeCity                             Yorba Linda
State                                             CA
PracticeZip                                    96161
FacilityPhone                             9519299890
PracticePhone                             8663890211
Fax                                       9049980299
BillingAddress1                      P.O. Box 105159
BillingAddress2                                  NaN
BillingCity                                  Atlanta
BillingState                                      GA
BillingZip                                30348-5159
BillingPhone                              8663890211
BillingFax                                9049980299
PLgroupNPI                           1073552378021.0
SB863ConfirmationDate            2022-01-01 00:00:00
PhysicalTherapistNPI                       954814783
ServiceFacilityNPI                      6194602805.0
ReferralOnly                                       Y
AcceptingWCPatients                                Y
dtype: object

In [52]:
align.min()

C:\Users\wecep\AppData\Local\Temp/ipykernel_3364/391082504.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  align.min()

Tier                                              -1
RecordID                                         424
ProviderEntityID                                5282
Group Name                            Align Networks
Facility Name                   DR LAURA SCIURBA LAC
ProviderEmail            Referrals@AlignNetworks.com
ProviderMiddleName                               NaN
Facility Tax ID                            2680188.0
Provider Tax ID                            270276119
Degree                                           NaN
PrimarySpecialty                         Acupuncture
PracticeStreet1                 1 CIVIC CENTER PLAZA
PracticeStreet2                                  NaN
PracticeCity                                   ACTON
State                                             CA
PracticeZip                                    82870
FacilityPhone                             2092070849
PracticePhone                             8663890211
Fax                                       9049980299
BillingAddress1                      P.O. Box 105159
BillingAddress2                                  NaN
BillingCity                                  Atlanta
BillingState                                      GA
BillingZip                                30348-5159
BillingPhone                              8663890211
BillingFax                                9049980299
PLgroupNPI                               103202126.0
SB863ConfirmationDate            2022-01-01 00:00:00
PhysicalTherapistNPI
ServiceFacilityNPI                       100301645.0
ReferralOnly                                       Y
AcceptingWCPatients                                Y
dtype: object

In [53]:
align.PrimarySpecialty

0                  Acupuncture
1             Physical Therapy
2             Physical Therapy
3             Physical Therapy
4             Physical Therapy
                 ...
25705         Physical Therapy
25706         Physical Therapy
25707              Acupuncture
25708    Chiropractic Services
25709         Physical Therapy
Name: PrimarySpecialty, Length: 25710, dtype: object

In [54]:
align["PrimarySpecialty"].head().sort_values()

0         Acupuncture
1    Physical Therapy
2    Physical Therapy
3    Physical Therapy
4    Physical Therapy
Name: PrimarySpecialty, dtype: object

In [55]:
align["PrimarySpecialty"].tail().sort_values()

25707              Acupuncture
25708    Chiropractic Services
25705         Physical Therapy
25706         Physical Therapy
25709         Physical Therapy
Name: PrimarySpecialty, dtype: object

In [56]:
align["PrimarySpecialty"].sort_values().tail()

8605     Physical Therapy
8604     Physical Therapy
8603     Physical Therapy
8613     Physical Therapy
25709    Physical Therapy
Name: PrimarySpecialty, dtype: object

In [57]:
align["PrimarySpecialty"].sort_values().head()

0        Acupuncture
24261    Acupuncture
24262    Acupuncture
24263    Acupuncture
24264    Acupuncture
Name: PrimarySpecialty, dtype: object

In [58]:
align[["PrimarySpecialty","Facility Name","PracticeCity"]]

,PrimarySpecialty,Facility Name,PracticeCity
0,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
1,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO
2,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON
3,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES
4,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO
...,...,...,...
25705,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY
25706,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY
25707,Acupuncture,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",BURBANK
25708,Chiropractic Services,Andy Truongvinh dba Andy Truongvinh Chiropractic,REDWOOD CITY
25709,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY

In [65]:
align[["PrimarySpecialty","Facility Name","PracticeCity"]].sort_values(by="PracticeCity").head(10)

,PrimarySpecialty,Facility Name,PracticeCity
23828,Acupuncture,Acton Acupuncture & Alternative Healing Center...,ACTON
23829,Acupuncture,Acton Acupuncture & Alternative Healing Center...,ACTON
12300,Physical Therapy,"Santiago Physical Therapy, Inc",ACTON
12299,Physical Therapy,"Santiago Physical Therapy, Inc",ACTON
14077,Physical Therapy,Santiyago Physical Therapy,ACTON
25425,Chiropractic Services,Agoura Family Chiropractic,AGOURA HILLS
25424,Chiropractic Services,Agoura Family Chiropractic,AGOURA HILLS
25426,Chiropractic Services,Agoura Family Chiropractic,AGOURA HILLS
3800,Physical Therapy,East & West Acupuncture Clicnic Inc,AGOURA HILLS
15925,Physical Therapy,CALIFORNIA LUNA CARE PHYSICAL THERAPY PC-Mobil...,ALAMEDA

In [66]:
align[["PrimarySpecialty","Facility Name","PracticeCity"]].sort_values(by="PrimarySpecialty").head(10)

,PrimarySpecialty,Facility Name,PracticeCity
0,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
24261,Acupuncture,"Charles Thomas Savoca dba Charles Savoca, Lice...",MONTEREY
24262,Acupuncture,HealthMerica Inc,FULLERTON
24263,Acupuncture,Celina Chua dba K.L. Family Acupuncture & Herb...,UPLAND
24264,Acupuncture,Shiva Rouhani dba Acupuncture Wellness Center,WEST COVINA
24265,Acupuncture,"BonWellness Clinic, Inc dba Bon Wellness Clinic",BUENA PARK
24266,Acupuncture,"BonWellness Clinic, Inc dba Bon Wellness Clinic",BUENA PARK
24267,Acupuncture,Jun Mi Yi DBA Barnabas Healing Center,POMONA
24268,Acupuncture,K&Y Acupuncture Inc,FULLERTON
24269,Acupuncture,Jeungmo Kim DBA Bethesda Acupuncture,CYPRESS

In [67]:
align.sort_values(by="PracticeCity")

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
23828,7,85031,106999,Align Networks,Acton Acupuncture & Alternative Healing Center...,Referrals@AlignNetworks.com,Marina,NaN,I McNutt,50622410.0,...,30348-5159,8663890211,9049980299,1.760574e+09,2022-01-01,1760573554,1.760574e+09,Y,Y,tcmways2003@yahoo.com
23829,7,85031,106999,Align Networks,Acton Acupuncture & Alternative Healing Center...,Referrals@AlignNetworks.com,MARINA,NaN,IVICA MCNUTT,50622410.0,...,30348-5159,8663890211,9049980299,1.760574e+09,2022-01-01,1215904748,1.760574e+09,Y,Y,tcmways2003@yahoo.com
12300,3,13291,46652,Align Networks,"Santiago Physical Therapy, Inc",Referrals@AlignNetworks.com,Susan,NaN,B. DiMartini,320231316.0,...,30348-5159,8663890211,9049980299,1.821141e+09,2022-01-01,1225115611,1.821141e+09,Y,Y,c.willey@handspluspt.com
12299,3,13291,46652,Align Networks,"Santiago Physical Therapy, Inc",Referrals@AlignNetworks.com,Patty,NaN,Jakobi-Stopper,320231316.0,...,30348-5159,8663890211,9049980299,1.821141e+09,2022-01-01,1437171279,1.821141e+09,Y,Y,c.willey@handspluspt.com
14077,3,101744,176096,Align Networks,Santiyago Physical Therapy,Referrals@AlignNetworks.com,NaN,NaN,NaN,472436400.0,...,30348-5159,8663890211,9049980299,NaN,2022-01-01,,1.821141e+09,Y,Y,david.girard@handspluspt.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18383,4,10799,45859,Align Networks,"H.D.P.R.G.,Inc DBA Hi-Desert Physical Rehabili...",Referrals@AlignNetworks.com,Jennifer,NaN,Diemart,721575853.0,...,30348-5159,8663890211,9049980299,1.295886e+09,2022-01-01,1043484850,1.295886e+08,Y,Y,officeyv@hdprg.com
18394,4,10799,45859,Align Networks,"H.D.P.R.G.,Inc DBA Hi-Desert Physical Rehabili...",Referrals@AlignNetworks.com,Rudy,NaN,Rones,721575853.0,...,30348-5159,8663890211,9049980299,1.295886e+09,2022-01-01,1700330602,1.295886e+08,Y,Y,officeyv@hdprg.com
18377,4,10799,45859,Align Networks,"H.D.P.R.G.,Inc DBA Hi-Desert Physical Rehabili...",Referrals@AlignNetworks.com,ERIN,NaN,BENNETTE,721575853.0,...,30348-5159,8663890211,9049980299,1.295886e+09,2022-01-01,1417589375,1.295886e+08,Y,Y,officeyv@hdprg.com
24764,8,67807,72322,Align Networks,East Canyon Chiropractic,Referrals@AlignNetworks.com,Terry,NaN,W. Wilson,330503055.0,...,30348-5159,8663890211,9049980299,1.790839e+09,2022-01-01,1558559690,1.558560e+09,Y,Y,NaN
11521,3,118508,45171,Align Networks,Salinas Physical Therapy Sports Medicine,Referrals@AlignNetworks.com,NaN,NaN,NaN,200750210.0,...,30348-5159,8663890211,9049980299,NaN,2022-01-01,,1.689707e+08,Y,Y,NaN

In [70]:
align[["ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]].sort_values(by="ProviderEntityID", ascending = True)

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
5,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
6,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
7,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
8,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
9,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
...,...,...,...,...
23684,187712,Physical Therapy,Rise Physical Therapy,IRVINE
23685,187713,Physical Therapy,Rise Physical Therapy,HUNTINGTON BEACH
23686,187714,Physical Therapy,Rise Physical Therapy,VISTA
23687,187715,Physical Therapy,Rise Physical Therapy,SAN DIEGO
23688,187716,Physical Therapy,Rise Physical Therapy,SAN DIEGO

In [73]:
align[["ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]].sort_values(by=["ProviderEntityID","PrimarySpecialty"], ascending = True)

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
5,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
6,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
7,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
8,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
9,5282,Physical Therapy,Concentra Medical Centers,Santa Clara
...,...,...,...,...
23684,187712,Physical Therapy,Rise Physical Therapy,IRVINE
23685,187713,Physical Therapy,Rise Physical Therapy,HUNTINGTON BEACH
23686,187714,Physical Therapy,Rise Physical Therapy,VISTA
23687,187715,Physical Therapy,Rise Physical Therapy,SAN DIEGO
23688,187716,Physical Therapy,Rise Physical Therapy,SAN DIEGO

In [74]:
align[["ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]].sort_values(by=["PrimarySpecialty","ProviderEntityID"], ascending = True)

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
23689,59840,Acupuncture,"Robin Farkas Hays, L.Ac., DNBAO",MILPITAS
23690,59840,Acupuncture,"Robin Farkas Hays, L.Ac., DNBAO",MILPITAS
23691,71656,Acupuncture,GQC Acupuncture Clinic,SHERMAN OAKS
23692,71656,Acupuncture,GQC Acupuncture Clinic,SHERMAN OAKS
23693,74463,Acupuncture,"Chinese Medicine & Acupuncture Institute, INC",WESTMINSTER
...,...,...,...,...
23684,187712,Physical Therapy,Rise Physical Therapy,IRVINE
23685,187713,Physical Therapy,Rise Physical Therapy,HUNTINGTON BEACH
23686,187714,Physical Therapy,Rise Physical Therapy,VISTA
23687,187715,Physical Therapy,Rise Physical Therapy,SAN DIEGO
23688,187716,Physical Therapy,Rise Physical Therapy,SAN DIEGO

In [78]:
align.sort_values(by=["PrimarySpecialty","ProviderEntityID","PracticeCity"], ascending = True).head()

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
23689,7,17490,59840,Align Networks,"Robin Farkas Hays, L.Ac., DNBAO",Referrals@AlignNetworks.com,Robin,NaN,F Hays,770304460.0,...,30348-5159,8663890211,9049980299,1.821153e+09,2022-01-01,1821152679,1.821153e+08,Y,Y,robinhays1@gmail.com
23690,7,17490,59840,Align Networks,"Robin Farkas Hays, L.Ac., DNBAO",Referrals@AlignNetworks.com,Robin,NaN,Hays,770304460.0,...,30348-5159,8663890211,9049980299,1.821153e+09,2022-01-01,1821152679,1.821153e+08,Y,Y,robinhays1@gmail.com
23691,7,57242,71656,Align Networks,GQC Acupuncture Clinic,Referrals@AlignNetworks.com,NaN,NaN,NaN,10653219.0,...,30348-5159,8663890211,9049980299,1.750352e+09,2022-01-01,,1.750352e+08,Y,Y,Ginaqcla@hotmail.com
23692,7,57242,71656,Align Networks,GQC Acupuncture Clinic,Referrals@AlignNetworks.com,Gina,NaN,Hua Qin Chuang,10653219.0,...,30348-5159,8663890211,9049980299,1.750352e+09,2022-01-01,1831170786,1.750352e+08,Y,Y,Ginaqcla@hotmail.com
23693,7,54073,74463,Align Networks,"Chinese Medicine & Acupuncture Institute, INC",Referrals@AlignNetworks.com,Gui,NaN,Jun Zhoa,954598272.0,...,30348-5159,8663890211,9049980299,1.538360e+09,2022-01-01,1457488678,1.700950e+09,Y,Y,Goldenwestclinic@gmail.com

In [79]:
align.sort_index(inplace = True)
align.head()

,Tier,RecordID,ProviderEntityID,Group Name,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
0,-1,84142,125861,Align Networks,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,...,30348-5159,8663890211,9049980299,1.609948e+09,2022-01-01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
1,-1,103764,129343,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022-01-01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
2,-1,106784,136107,Align Networks,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,...,30348-5159,8663890211,9049980299,NaN,2022-01-01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
3,-1,122878,167566,Align Networks,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,...,30348-5159,8663890211,9049980299,1.912411e+09,2022-01-01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
4,-1,131499,184425,Align Networks,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,...,30348-5159,8663890211,9049980299,1.740638e+09,2022-01-01,,1.740638e+09,Y,Y,Erika@williams-st-services.com

In [80]:
align.sort_index(axis = 1)
align.sort_index(axis = "columns", inplace = True)

In [81]:
align.head()

,AcceptingWCPatients,BillingAddress1,BillingAddress2,BillingCity,BillingFax,BillingPhone,BillingState,BillingZip,Degree,Facility Name,...,ProviderFirstName,ProviderLastName,ProviderMiddleName,RecordID,ReferralOnly,RenderingProviderEmail,SB863ConfirmationDate,ServiceFacilityNPI,State,Tier
0,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,NaN,Jingyu Liu dba Acupuncture & Herbal Medicine,...,Jingyu,Liu,NaN,84142,Y,acupuncture.jliu@gmail.com,2022-01-01,1.609948e+08,CA,-1
1,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,NaN,Palm Imaging Institute A Medical Corporation D...,...,NaN,NaN,NaN,103764,Y,cmaiden@empireorthopediccenter.net,2022-01-01,1.063411e+09,CA,-1
2,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,NaN,Palm Imaging Institute A Medical Corporation D...,...,Steve,Zecker,NaN,106784,Y,Klopez@empireorthopediccenter.net,2022-01-01,1.063411e+09,CA,-1
3,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,NaN,Haeseong Integrative Medicine Center,...,On,Jung Park,NaN,122878,Y,haeseongcenter@gmail.com,2022-01-01,1.619254e+09,CA,-1
4,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,NaN,"William Speech Therapy Services, Inc",...,NaN,NaN,NaN,131499,Y,Erika@williams-st-services.com,2022-01-01,1.740638e+09,CA,-1

In [82]:
align.iloc[350]

AcceptingWCPatients                                                       Y
BillingAddress1                                             P.O. Box 105159
BillingAddress2                                                         NaN
BillingCity                                                         Atlanta
BillingFax                                                       9049980299
BillingPhone                                                     8663890211
BillingState                                                             GA
BillingZip                                                       30348-5159
Degree                                                                  NaN
Facility Name             Matrix Rehabilitation  Inc. dba Select Physica...
Facility Tax ID                                                 710783147.0
FacilityPhone                                                    8317248235
Fax                                                              9049980299
Group Name                                                   Align Networks
License                                                                 NaN
PLgroupNPI                                                     1114962636.0
PhysicalTherapistNPI
PracticeCity                                                    WATSONVILLE
PracticePhone                                                    8663890211
PracticeStreet1                                       15 Penny Lane Suite 4
PracticeStreet2                                                         NaN
PracticeZip                                                           95076
PrimarySpecialty                                           Physical Therapy
Provider Tax ID                                                   270276119
ProviderEmail                                   Referrals@AlignNetworks.com
ProviderEntityID                                                      45778
ProviderFirstName                                                       NaN
ProviderLastName                                                        NaN
ProviderMiddleName                                                      NaN
RecordID                                                                424
ReferralOnly                                                              Y
RenderingProviderEmail                                                  NaN
SB863ConfirmationDate                                   2022-01-01 00:00:00
ServiceFacilityNPI                                              111496263.0
State                                                                    CA
Tier                                                                      1
Name: 350, dtype: object

In [87]:
align[["ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]].iloc[[350, 355,1000]]

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
350,45778,Physical Therapy,Matrix Rehabilitation Inc. dba Select Physica...,WATSONVILLE
355,45782,Physical Therapy,May Mardini dba Recovery Physical Therapy,STOCKTON
1000,55993,Physical Therapy,"MDRS Spine & Sport, Inc",CHULA VISTA

In [93]:
align[["ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]].iloc[350:355]

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
350,45778,Physical Therapy,Matrix Rehabilitation Inc. dba Select Physica...,WATSONVILLE
351,45782,Physical Therapy,May Mardini dba Recovery Physical Therapy,STOCKTON
352,45782,Physical Therapy,May Mardini dba Recovery Physical Therapy,STOCKTON
353,45782,Physical Therapy,May Mardini dba Recovery Physical Therapy,STOCKTON
354,45782,Physical Therapy,May Mardini dba Recovery Physical Therapy,STOCKTON

In [99]:
align.sort_index(inplace = True)

In [100]:
align[["ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]].head()

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
0,125861,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
1,129343,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO
2,136107,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON
3,167566,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES
4,184425,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO

In [101]:
align.head()

,level_0,index,AcceptingWCPatients,BillingAddress1,BillingAddress2,BillingCity,BillingFax,BillingPhone,BillingState,BillingZip,...,ProviderFirstName,ProviderLastName,ProviderMiddleName,RecordID,ReferralOnly,RenderingProviderEmail,SB863ConfirmationDate,ServiceFacilityNPI,State,Tier
0,0,0,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,...,Jingyu,Liu,NaN,84142,Y,acupuncture.jliu@gmail.com,2022-01-01,1.609948e+08,CA,-1
1,1,1,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,...,NaN,NaN,NaN,103764,Y,cmaiden@empireorthopediccenter.net,2022-01-01,1.063411e+09,CA,-1
2,2,2,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,...,Steve,Zecker,NaN,106784,Y,Klopez@empireorthopediccenter.net,2022-01-01,1.063411e+09,CA,-1
3,3,3,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,...,On,Jung Park,NaN,122878,Y,haeseongcenter@gmail.com,2022-01-01,1.619254e+09,CA,-1
4,4,4,Y,P.O. Box 105159,NaN,Atlanta,9049980299,8663890211,GA,30348-5159,...,NaN,NaN,NaN,131499,Y,Erika@williams-st-services.com,2022-01-01,1.740638e+09,CA,-1

In [102]:
newAlign=align[["ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]]

In [104]:
newAlign.head()

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
0,125861,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
1,129343,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO
2,136107,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON
3,167566,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES
4,184425,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO

In [105]:
newAlign.sort_index()

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
0,125861,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
1,129343,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO
2,136107,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON
3,167566,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES
4,184425,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO
...,...,...,...,...
25705,178810,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY
25706,178810,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY
25707,181692,Acupuncture,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",BURBANK
25708,65334,Chiropractic Services,Andy Truongvinh dba Andy Truongvinh Chiropractic,REDWOOD CITY
25709,149192,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY

In [112]:
newAlign.sort_index(axis =0).head()

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
0,125861,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
1,129343,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO
2,136107,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON
3,167566,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES
4,184425,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO

In [118]:
newAlign.sort_index(axis =1).head()

,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID
0,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH,Acupuncture,125861
1,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO,Physical Therapy,129343
2,Palm Imaging Institute A Medical Corporation D...,COLTON,Physical Therapy,136107
3,Haeseong Integrative Medicine Center,LOS ANGELES,Physical Therapy,167566
4,"William Speech Therapy Services, Inc",ENCINO,Physical Therapy,184425

In [121]:
newAlign.sort_index(axis ="columns", inplace = True)

In [122]:
newAlign.head()

,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID
0,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH,Acupuncture,125861
1,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO,Physical Therapy,129343
2,Palm Imaging Institute A Medical Corporation D...,COLTON,Physical Therapy,136107
3,Haeseong Integrative Medicine Center,LOS ANGELES,Physical Therapy,167566
4,"William Speech Therapy Services, Inc",ENCINO,Physical Therapy,184425

In [128]:
newAlign.loc(1)

In [129]:
newAlign.head()

,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID
0,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH,Acupuncture,125861
1,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO,Physical Therapy,129343
2,Palm Imaging Institute A Medical Corporation D...,COLTON,Physical Therapy,136107
3,Haeseong Integrative Medicine Center,LOS ANGELES,Physical Therapy,167566
4,"William Speech Therapy Services, Inc",ENCINO,Physical Therapy,184425

In [130]:
newAlign.iloc[350]

Facility Name       Matrix Rehabilitation  Inc. dba Select Physica...
PracticeCity                                              WATSONVILLE
PrimarySpecialty                                     Physical Therapy
ProviderEntityID                                                45778
Name: 350, dtype: object

In [138]:
newAlign.iloc[-35:-33]

,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID
25675,Advanced Acupuncture Inc,SANTA MONICA,Acupuncture,126247
25676,Advanced Acupuncture Inc,SANTA MONICA,Acupuncture,126247

In [139]:
newAlign.reset_index(inplace = True)

In [140]:
newAlign.head()

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID
0,0,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH,Acupuncture,125861
1,1,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO,Physical Therapy,129343
2,2,Palm Imaging Institute A Medical Corporation D...,COLTON,Physical Therapy,136107
3,3,Haeseong Integrative Medicine Center,LOS ANGELES,Physical Therapy,167566
4,4,"William Speech Therapy Services, Inc",ENCINO,Physical Therapy,184425

In [141]:
newAlign.tail()

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID
25705,25705,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Physical Therapy,178810
25706,25706,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Physical Therapy,178810
25707,25707,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",BURBANK,Acupuncture,181692
25708,25708,Andy Truongvinh dba Andy Truongvinh Chiropractic,REDWOOD CITY,Chiropractic Services,65334
25709,25709,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Physical Therapy,149192

In [150]:
newAlign.loc["index","PracticeCity"]="DOWNEY"

C:\Users\wecep\AppData\Local\Temp/ipykernel_3364/1479290052.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newAlign.loc["index","PracticeCity"]="DOWNEY"

In [151]:
newAlign["PracticeCity"]=="DOWNEY"

0        True
1        True
2        True
3        True
4        True
         ...
25706    True
25707    True
25708    True
25709    True
index    True
Name: PracticeCity, Length: 25711, dtype: bool

In [164]:
newAlign["PracticeCity"]=="LOS ANGELES"

0        False
1        False
2        False
3        False
4        False
         ...
25706    False
25707    False
25708    False
25709    False
index    False
Name: PracticeCity, Length: 25711, dtype: bool

In [165]:
is_Downey = newAlign["PracticeCity"]=="DOWNEY"

In [166]:
is_losAngeles

0        True
1        True
2        True
3        True
4        True
         ...
25706    True
25707    True
25708    True
25709    True
index    True
Name: PracticeCity, Length: 25711, dtype: bool

In [169]:
newAlign[is_Downey].head()

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID,"(0, PracticeCity)"
0,0.0,Jingyu Liu dba Acupuncture & Herbal Medicine,DOWNEY,Acupuncture,125861.0,DOWNEY
1,1.0,Palm Imaging Institute A Medical Corporation D...,DOWNEY,Physical Therapy,129343.0,DOWNEY
2,2.0,Palm Imaging Institute A Medical Corporation D...,DOWNEY,Physical Therapy,136107.0,DOWNEY
3,3.0,Haeseong Integrative Medicine Center,DOWNEY,Physical Therapy,167566.0,DOWNEY
4,4.0,"William Speech Therapy Services, Inc",DOWNEY,Physical Therapy,184425.0,DOWNEY

In [170]:
acu = newAlign["PrimarySpecialty"]=="Acupuncture"
newAlign[acu].head()

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID,"(0, PracticeCity)"
0,0.0,Jingyu Liu dba Acupuncture & Herbal Medicine,DOWNEY,Acupuncture,125861.0,DOWNEY
2891,2891.0,Won Hee Cho DBA True Healing Acupuncture,DOWNEY,Acupuncture,170446.0,DOWNEY
3150,3150.0,"United University of Los Angeles, Inc. DBA Uni...",DOWNEY,Acupuncture,113636.0,DOWNEY
3151,3151.0,"United University of Los Angeles, Inc. DBA Uni...",DOWNEY,Acupuncture,113636.0,DOWNEY
3152,3152.0,"United University of Los Angeles, Inc. DBA Uni...",DOWNEY,Acupuncture,113636.0,DOWNEY

In [176]:
ent = newAlign["ProviderEntityID"]> 185000
newAlign[ent].head()

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID,"(0, PracticeCity)"
189,189.0,Concentra Medical Centers,DOWNEY,Physical Therapy,185906.0,DOWNEY
190,190.0,Concentra Medical Centers,DOWNEY,Physical Therapy,185908.0,DOWNEY
4738,4738.0,Concentra Medical Centers,DOWNEY,Physical Therapy,185614.0,DOWNEY
4739,4739.0,Concentra Medical Centers,DOWNEY,Physical Therapy,185614.0,DOWNEY
4740,4740.0,Concentra Medical Centers,DOWNEY,Physical Therapy,185614.0,DOWNEY

In [177]:
newAlign[acu & ent]

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID,"(0, PracticeCity)"
4796,4796.0,Jin Wook Choi dba MAUM ACUPUNCTURE CLINIC,DOWNEY,Acupuncture,186672.0,DOWNEY
24594,24594.0,Jin Kyou Lim DBA Lims Acupuncture Clinic,DOWNEY,Acupuncture,185067.0,DOWNEY
24595,24595.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,185659.0,DOWNEY
24596,24596.0,Bradley Cimino LACdba Pro Active Acupuncture Inc,DOWNEY,Acupuncture,185856.0,DOWNEY
24597,24597.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,185977.0,DOWNEY
24598,24598.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,186602.0,DOWNEY
24599,24599.0,Karen Ann Fisher DBA Alpine Acupuncture,DOWNEY,Acupuncture,186616.0,DOWNEY
24600,24600.0,KSJ Acupuncture Clinic Inc,DOWNEY,Acupuncture,186780.0,DOWNEY
24601,24601.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,186930.0,DOWNEY
24602,24602.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,187009.0,DOWNEY
24603,24603.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,187012.0,DOWNEY
24604,24604.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,187145.0,DOWNEY
24605,24605.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,187147.0,DOWNEY
24606,24606.0,Myung Ahn. Chung dba Mac Acupuncture and Herbs,DOWNEY,Acupuncture,187199.0,DOWNEY
24607,24607.0,Tony Chung dba AyurAcu Health Group,DOWNEY,Acupuncture,187575.0,DOWNEY

In [178]:
newAlign[acu | ent]

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID,"(0, PracticeCity)"
0,0.0,Jingyu Liu dba Acupuncture & Herbal Medicine,DOWNEY,Acupuncture,125861.0,DOWNEY
189,189.0,Concentra Medical Centers,DOWNEY,Physical Therapy,185906.0,DOWNEY
190,190.0,Concentra Medical Centers,DOWNEY,Physical Therapy,185908.0,DOWNEY
2891,2891.0,Won Hee Cho DBA True Healing Acupuncture,DOWNEY,Acupuncture,170446.0,DOWNEY
3150,3150.0,"United University of Los Angeles, Inc. DBA Uni...",DOWNEY,Acupuncture,113636.0,DOWNEY
...,...,...,...,...,...,...
25665,25665.0,Chau AI Au dba Aus Acupuncture & Herb Clinic,DOWNEY,Acupuncture,114593.0,DOWNEY
25675,25675.0,Advanced Acupuncture Inc,DOWNEY,Acupuncture,126247.0,DOWNEY
25676,25676.0,Advanced Acupuncture Inc,DOWNEY,Acupuncture,126247.0,DOWNEY
25677,25677.0,United Alternative Medical Group Inc dba T.Y. ...,DOWNEY,Acupuncture,126560.0,DOWNEY
25707,25707.0,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",DOWNEY,Acupuncture,181692.0,DOWNEY

In [179]:
newAlign[~acu]

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID,"(0, PracticeCity)"
1,1.0,Palm Imaging Institute A Medical Corporation D...,DOWNEY,Physical Therapy,129343.0,DOWNEY
2,2.0,Palm Imaging Institute A Medical Corporation D...,DOWNEY,Physical Therapy,136107.0,DOWNEY
3,3.0,Haeseong Integrative Medicine Center,DOWNEY,Physical Therapy,167566.0,DOWNEY
4,4.0,"William Speech Therapy Services, Inc",DOWNEY,Physical Therapy,184425.0,DOWNEY
5,5.0,Concentra Medical Centers,DOWNEY,Physical Therapy,5282.0,DOWNEY
...,...,...,...,...,...,...
25705,25705.0,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Physical Therapy,178810.0,DOWNEY
25706,25706.0,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Physical Therapy,178810.0,DOWNEY
25708,25708.0,Andy Truongvinh dba Andy Truongvinh Chiropractic,DOWNEY,Chiropractic Services,65334.0,DOWNEY
25709,25709.0,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Physical Therapy,149192.0,DOWNEY
index,NaN,NaN,DOWNEY,NaN,NaN,NaN

In [180]:
newAlign[newAlign["ProviderEntityID"].between(5000, 6000)].head()

,index,Facility Name,PracticeCity,PrimarySpecialty,ProviderEntityID,"(0, PracticeCity)"
5,5.0,Concentra Medical Centers,DOWNEY,Physical Therapy,5282.0,DOWNEY
6,6.0,Concentra Medical Centers,DOWNEY,Physical Therapy,5282.0,DOWNEY
7,7.0,Concentra Medical Centers,DOWNEY,Physical Therapy,5282.0,DOWNEY
8,8.0,Concentra Medical Centers,DOWNEY,Physical Therapy,5282.0,DOWNEY
9,9.0,Concentra Medical Centers,DOWNEY,Physical Therapy,5282.0,DOWNEY

In [181]:
Align = pd.read_csv("C:/Users/wecep/Objectel/ListTest.csv", index_col="Group Name",low_memory=False)

In [182]:
Align.head()

,Tier,RecordID,ProviderEntityID,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,Provider Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
Group Name,,,,,,,,,,,,,,,,,,,,,
Align Networks,-1,84142,125861,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,270276119,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
Align Networks,-1,103764,129343,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
Align Networks,-1,106784,136107,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
Align Networks,-1,122878,167566,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,270276119,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
Align Networks,-1,131499,184425,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,270276119,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com

In [183]:
newA = align[["ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]]

In [184]:
newA

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
0,125861,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
1,129343,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO
2,136107,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON
3,167566,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES
4,184425,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO
...,...,...,...,...
25705,178810,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY
25706,178810,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY
25707,181692,Acupuncture,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",BURBANK
25708,65334,Chiropractic Services,Andy Truongvinh dba Andy Truongvinh Chiropractic,REDWOOD CITY
25709,149192,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY

In [185]:
newA["PrimarySpecialty"].head()

0         Acupuncture
1    Physical Therapy
2    Physical Therapy
3    Physical Therapy
4    Physical Therapy
Name: PrimarySpecialty, dtype: object

In [186]:
newA["PrimarySpecialty"].head().values

array(['Acupuncture', 'Physical Therapy', 'Physical Therapy',
       'Physical Therapy', 'Physical Therapy'], dtype=object)

In [187]:
newA["PrimarySpecialty"].str

In [188]:
newA["PrimarySpecialty"].str.lstrip().head()

0         Acupuncture
1    Physical Therapy
2    Physical Therapy
3    Physical Therapy
4    Physical Therapy
Name: PrimarySpecialty, dtype: object

In [189]:
newA["PrimarySpecialty"].str.rstrip().head()

0         Acupuncture
1    Physical Therapy
2    Physical Therapy
3    Physical Therapy
4    Physical Therapy
Name: PrimarySpecialty, dtype: object

In [190]:
newA["PrimarySpecialty"].str.strip().head()

0         Acupuncture
1    Physical Therapy
2    Physical Therapy
3    Physical Therapy
4    Physical Therapy
Name: PrimarySpecialty, dtype: object

In [213]:
newA.columns

Index(['ProviderEntityID', 'PrimarySpecialty', 'Facility Name',
       'PracticeCity'],
      dtype='object')

In [197]:
for column in newA.columns:
    print(column)
    if column.isnumeric == False:
        newA[column] = newA[column].str.strip()

ProviderEntityID
PrimarySpecialty
Facility Name
PracticeCity

In [198]:
len(newA)

25710

In [199]:
newA["PrimarySpecialty"].unique()

array(['Acupuncture', 'Physical Therapy', 'Chiropractic Services',
       'Massage Therapy', 'Could be All'], dtype=object)

In [200]:
newA["PrimarySpecialty"].str.lower().str.contains("all").head()

0    False
1    False
2    False
3    False
4    False
Name: PrimarySpecialty, dtype: bool

In [201]:
hasAll = newA["PrimarySpecialty"].str.lower().str.contains("all")
newA[hasAll]

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
25646,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25647,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25648,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25649,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25650,144616,Could be All,Concentra Medical Centers,SACRAMENTO

In [205]:
newA[hasAll].head()

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
25646,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25647,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25648,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25649,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25650,144616,Could be All,Concentra Medical Centers,SACRAMENTO

In [215]:
startP = newA["PrimarySpecialty"].str.lower().str.startswith("co")
newA[startP]

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
25646,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25647,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25648,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25649,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25650,144616,Could be All,Concentra Medical Centers,SACRAMENTO

In [217]:
endP = newA["PrimarySpecialty"].str.lower().str.endswith("ll")
newA[endP]

,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
25646,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25647,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25648,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25649,46677,Could be All,Concentra Medical Centers,RIVERSIDE
25650,144616,Could be All,Concentra Medical Centers,SACRAMENTO

In [3]:
Align = pd.read_csv("C:/Users/wecep/Objectel/ListTest.csv", index_col="Group Name",low_memory=False)

In [4]:
Align.columns

Index(['Tier', 'RecordID', 'ProviderEntityID', 'Facility Name',
       'ProviderEmail', 'ProviderFirstName', 'ProviderMiddleName',
       'ProviderLastName', 'Facility Tax ID', 'Provider Tax ID', 'Degree',
       'License', 'PrimarySpecialty', 'PracticeStreet1', 'PracticeStreet2',
       'PracticeCity', 'State', 'PracticeZip', 'FacilityPhone',
       'PracticePhone', 'Fax', 'BillingAddress1', 'BillingAddress2',
       'BillingCity', 'BillingState', 'BillingZip', 'BillingPhone',
       'BillingFax', 'PLgroupNPI', 'SB863ConfirmationDate',
       'PhysicalTherapistNPI', 'ServiceFacilityNPI', 'ReferralOnly',
       'AcceptingWCPatients', 'RenderingProviderEmail'],
      dtype='object')

In [6]:
provider = Align[["ProviderFirstName", "ProviderMiddleName","ProviderLastName","ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]]

In [7]:
provider.head()

,ProviderFirstName,ProviderMiddleName,ProviderLastName,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
Group Name,,,,,,,
Align Networks,Jingyu,NaN,Liu,125861,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
Align Networks,NaN,NaN,NaN,129343,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO
Align Networks,Steve,NaN,Zecker,136107,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON
Align Networks,On,NaN,Jung Park,167566,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES
Align Networks,NaN,NaN,NaN,184425,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO

In [8]:
provider["ProviderFirstName"].str.len().head()

Group Name
Align Networks    6.0
Align Networks    NaN
Align Networks    5.0
Align Networks    2.0
Align Networks    NaN
Name: ProviderFirstName, dtype: float64

In [10]:
provider["Facility Name"].str.split(" ").head()

Group Name
Align Networks    [Jingyu, Liu, dba, Acupuncture, &, Herbal, Med...
Align Networks    [Palm, Imaging, Institute, A, Medical, Corpora...
Align Networks    [Palm, Imaging, Institute, A, Medical, Corpora...
Align Networks            [Haeseong, Integrative, Medicine, Center]
Align Networks           [William, Speech, Therapy, Services,, Inc]
Name: Facility Name, dtype: object

In [11]:
provider["PrimarySpecialty"].str.split(" ").head()

Group Name
Align Networks          [Acupuncture]
Align Networks    [Physical, Therapy]
Align Networks    [Physical, Therapy]
Align Networks    [Physical, Therapy]
Align Networks    [Physical, Therapy]
Name: PrimarySpecialty, dtype: object

In [13]:
phone_number = '"555"|"-123"|"4567"'
phone_number.split('"|"')

['"555', '-123', '4567"']

In [15]:
phone_number[0]

'"'

In [16]:
provider["Facility Name"].str.split(" ", n=1).head()

Group Name
Align Networks      [Jingyu, Liu dba Acupuncture & Herbal Medicine]
Align Networks    [Palm, Imaging Institute A Medical Corporation...
Align Networks    [Palm, Imaging Institute A Medical Corporation...
Align Networks              [Haeseong, Integrative Medicine Center]
Align Networks              [William, Speech Therapy Services, Inc]
Name: Facility Name, dtype: object

In [17]:
provider["Facility Name"].str.split(" ", n=1).str.get(0).head()

Group Name
Align Networks      Jingyu
Align Networks        Palm
Align Networks        Palm
Align Networks    Haeseong
Align Networks     William
Name: Facility Name, dtype: object

In [18]:
provider["Facility Name"].str.split(pat = " ", n=1, expand = True).head()

                       0                                                  1
Group Name
Align Networks    Jingyu              Liu dba Acupuncture & Herbal Medicine
Align Networks      Palm  Imaging Institute A Medical Corporation DBA-Em...
Align Networks      Palm  Imaging Institute A Medical Corporation DBA-Em...
Align Networks  Haeseong                        Integrative Medicine Center
Align Networks   William                       Speech Therapy Services, Inc

In [19]:
provider[["FirstName", "LastName"]]= provider["Facility Name"].str.split(pat = " ", n=1, expand = True)

C:\Users\wecep\anaconda3\lib\site-packages\pandas\core\frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [21]:
provider

,ProviderFirstName,ProviderMiddleName,ProviderLastName,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity,FirstName,LastName
Group Name,,,,,,,,,
Align Networks,Jingyu,NaN,Liu,125861,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH,Jingyu,Liu dba Acupuncture & Herbal Medicine
Align Networks,NaN,NaN,NaN,129343,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO,Palm,Imaging Institute A Medical Corporation DBA-Em...
Align Networks,Steve,NaN,Zecker,136107,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON,Palm,Imaging Institute A Medical Corporation DBA-Em...
Align Networks,On,NaN,Jung Park,167566,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES,Haeseong,Integrative Medicine Center
Align Networks,NaN,NaN,NaN,184425,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO,William,"Speech Therapy Services, Inc"
...,...,...,...,...,...,...,...,...,...
Align Networks,Mabel,NaN,Cobos,178810,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Advanced,Dynamics Physical Therapy DBA Matthew R. Perry
Align Networks,Matthew,NaN,Perry,178810,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Advanced,Dynamics Physical Therapy DBA Matthew R. Perry
Align Networks,NaN,NaN,NaN,181692,Acupuncture,"Alejandro J. Katz, Licensed Acupuncturist, Pai...",BURBANK,Alejandro,"J. Katz, Licensed Acupuncturist, Pain Manageme..."
Align Networks,DR,NaN,ANDY TRUONGVINH,65334,Chiropractic Services,Andy Truongvinh dba Andy Truongvinh Chiropractic,REDWOOD CITY,Andy,Truongvinh dba Andy Truongvinh Chiropractic
Align Networks,Matthew,NaN,R. Perry,149192,Physical Therapy,Advanced Dynamics Physical Therapy DBA Matthew...,DOWNEY,Advanced,Dynamics Physical Therapy DBA Matthew R. Perry

In [23]:
Spec = Align[["ProviderFirstName", "ProviderMiddleName","ProviderLastName","ProviderEntityID","PrimarySpecialty","Facility Name","PracticeCity"]]

In [24]:
Spec.head()

,ProviderFirstName,ProviderMiddleName,ProviderLastName,ProviderEntityID,PrimarySpecialty,Facility Name,PracticeCity
Group Name,,,,,,,
Align Networks,Jingyu,NaN,Liu,125861,Acupuncture,Jingyu Liu dba Acupuncture & Herbal Medicine,ANTIOCH
Align Networks,NaN,NaN,NaN,129343,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,SAN BERNARDINO
Align Networks,Steve,NaN,Zecker,136107,Physical Therapy,Palm Imaging Institute A Medical Corporation D...,COLTON
Align Networks,On,NaN,Jung Park,167566,Physical Therapy,Haeseong Integrative Medicine Center,LOS ANGELES
Align Networks,NaN,NaN,NaN,184425,Physical Therapy,"William Speech Therapy Services, Inc",ENCINO

In [25]:
Spec.pivot_table(index="PrimarySpecialty")

                       ProviderEntityID
PrimarySpecialty
Acupuncture               142422.599345
Chiropractic Services      98170.491388
Could be All               66264.800000
Massage Therapy           171801.965517
Physical Therapy          130405.011399

In [26]:
Spec.pivot_table(index = "PrimarySpecialty", aggfunc = "mean")

                       ProviderEntityID
PrimarySpecialty
Acupuncture               142422.599345
Chiropractic Services      98170.491388
Could be All               66264.800000
Massage Therapy           171801.965517
Physical Therapy          130405.011399

In [27]:
Spec.pivot_table(index = "PrimarySpecialty", aggfunc = "count")

,Facility Name,PracticeCity,ProviderEntityID,ProviderFirstName,ProviderLastName,ProviderMiddleName
PrimarySpecialty,,,,,,
Acupuncture,916,916,916,854,856,0
Chiropractic Services,987,987,987,986,987,0
Could be All,5,5,5,4,4,0
Massage Therapy,29,29,29,29,29,0
Physical Therapy,23773,23773,23773,23009,23052,0

In [28]:
Spec.pivot_table(index = "PrimarySpecialty", aggfunc = "sum")

                       ProviderEntityID  ProviderMiddleName
PrimarySpecialty
Acupuncture                   130459101                 0.0
Chiropractic Services          96894275                 0.0
Could be All                     331324                 0.0
Massage Therapy                 4982257                 0.0
Physical Therapy             3100118336                 0.0

In [29]:
Spec.pivot_table(index = "PrimarySpecialty", aggfunc = "sum", values="ProviderEntityID")

                       ProviderEntityID
PrimarySpecialty
Acupuncture                   130459101
Chiropractic Services          96894275
Could be All                     331324
Massage Therapy                 4982257
Physical Therapy             3100118336

In [30]:
Spec.pivot_table(index = "PrimarySpecialty", columns= "PracticeCity", aggfunc = "sum", values="ProviderEntityID")

PracticeCity,ACTON,AGOURA HILLS,ALAMEDA,ALHAMBRA,ALISO VIEJO,ALPINE,ANAHEIM,ANDERSON,ANGELS CAMP,ANTIOCH,...,West Sacramento,Westlake Village,Whittier,Woodland,Woodland Hills,YORBA LINDA,YUBA CITY,YUCAIPA,YUCCA VALLEY,Yorba Linda
PrimarySpecialty,,,,,,,,,,,,,,,,,,,,,
Acupuncture,213998.0,NaN,NaN,164005.0,NaN,186616.0,2495819.0,NaN,NaN,363472.0,...,NaN,NaN,NaN,NaN,NaN,136166.0,NaN,369064.0,NaN,NaN
Chiropractic Services,NaN,406854.0,118445.0,977332.0,NaN,NaN,1017319.0,NaN,NaN,NaN,...,83227.0,NaN,70085.0,83534.0,80984.0,NaN,155619.0,75253.0,134529.0,72322.0
Could be All,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Massage Therapy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Physical Therapy,269400.0,155285.0,4260083.0,2487947.0,2434877.0,NaN,17243666.0,268484.0,167393.0,4431441.0,...,140088.0,202852.0,NaN,NaN,176552.0,32100127.0,3206110.0,1315158.0,1513347.0,45171.0

In [31]:
Spec.pivot_table(index = "PrimarySpecialty", columns= "PracticeCity", aggfunc = "count", values="ProviderEntityID")

PracticeCity,ACTON,AGOURA HILLS,ALAMEDA,ALHAMBRA,ALISO VIEJO,ALPINE,ANAHEIM,ANDERSON,ANGELS CAMP,ANTIOCH,...,West Sacramento,Westlake Village,Whittier,Woodland,Woodland Hills,YORBA LINDA,YUBA CITY,YUCAIPA,YUCCA VALLEY,Yorba Linda
PrimarySpecialty,,,,,,,,,,,,,,,,,,,,,
Acupuncture,2.0,NaN,NaN,1.0,NaN,1.0,15.0,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN
Chiropractic Services,NaN,3.0,1.0,8.0,NaN,NaN,10.0,NaN,NaN,NaN,...,1.0,NaN,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0
Could be All,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Massage Therapy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Physical Therapy,3.0,1.0,23.0,19.0,24.0,NaN,160.0,4.0,1.0,24.0,...,3.0,2.0,NaN,NaN,2.0,182.0,36.0,13.0,33.0,1.0

In [32]:
Spec.pivot_table(
    index = "PrimarySpecialty", columns= "PracticeCity", aggfunc = "count", values="ProviderEntityID", 
    fill_value=0, margins=True)

PracticeCity,ACTON,AGOURA HILLS,ALAMEDA,ALHAMBRA,ALISO VIEJO,ALPINE,ANAHEIM,ANDERSON,ANGELS CAMP,ANTIOCH,...,Westlake Village,Whittier,Woodland,Woodland Hills,YORBA LINDA,YUBA CITY,YUCAIPA,YUCCA VALLEY,Yorba Linda,All
PrimarySpecialty,,,,,,,,,,,,,,,,,,,,,
Acupuncture,2,0,0,1,0,1,15,0,0,3,...,0,0,0,0,1,0,2,0,0,916
Chiropractic Services,0,3,1,8,0,0,10,0,0,0,...,0,1,1,1,0,1,1,1,1,987
Could be All,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
Massage Therapy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,29
Physical Therapy,3,1,23,19,24,0,160,4,1,24,...,2,0,0,2,182,36,13,33,1,23773
All,5,4,24,28,24,1,185,4,1,27,...,2,1,1,3,183,37,16,34,2,25710

In [36]:
data = pd.read_csv("C:/Users/wecep/Objectel/ListTest.csv", index_col="Group Name",low_memory=False)

In [37]:
data.head()

,Tier,RecordID,ProviderEntityID,Facility Name,ProviderEmail,ProviderFirstName,ProviderMiddleName,ProviderLastName,Facility Tax ID,Provider Tax ID,...,BillingZip,BillingPhone,BillingFax,PLgroupNPI,SB863ConfirmationDate,PhysicalTherapistNPI,ServiceFacilityNPI,ReferralOnly,AcceptingWCPatients,RenderingProviderEmail
Group Name,,,,,,,,,,,,,,,,,,,,,
Align Networks,-1,84142,125861,Jingyu Liu dba Acupuncture & Herbal Medicine,Referrals@AlignNetworks.com,Jingyu,NaN,Liu,616861912.0,270276119,...,30348-5159,8663890211,9049980299,1.609948e+09,2022/01/01,1609947886,1.609948e+08,Y,Y,acupuncture.jliu@gmail.com
Align Networks,-1,103764,129343,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,NaN,NaN,NaN,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,,1.063411e+09,Y,Y,cmaiden@empireorthopediccenter.net
Align Networks,-1,106784,136107,Palm Imaging Institute A Medical Corporation D...,Referrals@AlignNetworks.com,Steve,NaN,Zecker,330638761.0,270276119,...,30348-5159,8663890211,9049980299,NaN,2022/01/01,1881708923,1.063411e+09,Y,Y,Klopez@empireorthopediccenter.net
Align Networks,-1,122878,167566,Haeseong Integrative Medicine Center,Referrals@AlignNetworks.com,On,NaN,Jung Park,821523926.0,270276119,...,30348-5159,8663890211,9049980299,1.912411e+09,2022/01/01,1619254190,1.619254e+09,Y,Y,haeseongcenter@gmail.com
Align Networks,-1,131499,184425,"William Speech Therapy Services, Inc",Referrals@AlignNetworks.com,NaN,NaN,NaN,812420473.0,270276119,...,30348-5159,8663890211,9049980299,1.740638e+09,2022/01/01,,1.740638e+09,Y,Y,Erika@williams-st-services.com

In [38]:
%%writefile test.txt
Hello, this is a quick test file.

Writing test.txt

In [39]:
myfile = open('nba.csv')

In [40]:
pwd

'C:\\Users\\wecep\\iCloudDrive\\UDEMY\\04-06-2021-live-training-pandas-for-data-analysis'

In [42]:
# We can now read the file
myfile.read()

"Name,Team,Position,Birthday,Salary\nShake Milton,Philadelphia 76ers,SG,9/26/96,1445697\nChristian Wood,Detroit Pistons,PF,9/27/95,1645357\nPJ Washington,Charlotte Hornets,PF,8/23/98,3831840\nDerrick Rose,Detroit Pistons,PG,10/4/88,7317074\nMarial Shayok,Philadelphia 76ers,G,7/26/95,79568\nDraymond Green,Golden State Warriors,PF,3/4/90,18539130\nKendrick Nunn,Miami Heat,SG,8/3/95,1416852\nCedi Osman,Cleveland Cavaliers,SF,4/8/95,2907143\nBrook Lopez,Milwaukee Bucks,C,4/1/88,12093024\nTorrey Craig,Denver Nuggets,SF,12/19/90,2000000\nJordan Clarkson,Cleveland Cavaliers,PG,6/7/92,13437500\nAlex Caruso,Los Angeles Lakers,PG,2/28/94,2750000\nNorvel Pelle,Philadelphia 76ers,FC,2/3/93,79568\nTyler Johnson,Phoenix Suns,PG,5/7/92,19245370\nAlec Burks,Golden State Warriors,SG,7/20/91,2320044\nJaMychal Green,Los Angeles Clippers,PF,6/21/90,4767000\nDwight Howard,Los Angeles Lakers,C,12/8/85,5603850\nNikola Jokic,Denver Nuggets,C,2/19/95,27504630\nChris Boucher,Toronto Raptors,PF,1/11/93,1588231\nMarcus Morris,New York Knicks,PF,9/2/89,15000000\nKevin Huerter,Atlanta Hawks,SG,8/27/98,2636280\nRui Hachimura,Washington Wizards,PF,2/8/98,4469160\nGeorge Hill,Milwaukee Bucks,PG,5/4/86,10133907\nNickeil Alexander-Walker,New Orleans Pelicans,SG,9/2/98,2964840\nJaylen Hoard,Portland Trail Blazers,SF,3/30/99,79568\nTyler Cook,Cleveland Cavaliers,PF,9/23/97,79568\nOtto Porter,Chicago Bulls,SF,6/3/93,27250576\nLangston Galloway,Detroit Pistons,PG,12/9/91,7333333\nEvan Turner,Atlanta Hawks,PG,10/27/88,18606556\nNorman Powell,Toronto Raptors,SG,5/25/93,10116576\nNicolas Claxton,Brooklyn Nets,PF,4/17/99,898310\nMichael Frazier,Houston Rockets,G,3/8/94,79568\nPaul Millsap,Denver Nuggets,PF,2/10/85,30000000\nFurkan Korkmaz,Philadelphia 76ers,SG,7/24/97,1620564\nTrey Burke,Philadelphia 76ers,PG,11/12/92,2028594\nBradley Beal,Washington Wizards,SG,6/28/93,27093018\nThomas Bryant,Washington Wizards,C,7/31/97,8000000\nDean Wade,Cleveland Cavaliers,PF,11/20/96,79568\nChris Paul,Oklahoma City Thunder,PG,5/6/85,38506482\nJosh Hart,New Orleans Pelicans,SF,3/6/95,1934160\nLaMarcus Aldridge,San Antonio Spurs,C,7/19/85,26000000\nDaQuan Jeffries,Sacramento Kings,SG,8/30/97,898310\nHamidou Diallo,Oklahoma City Thunder,SF,7/31/98,1416852\nJamal Murray,Denver Nuggets,PG,2/23/97,4444746\nDarius Bazley,Oklahoma City Thunder,PF,6/12/00,2284800\nRobert Franks,Charlotte Hornets,F,12/18/96,79568\nGerald Green,Houston Rockets,SF,1/26/86,2564753\nThaddeus Young,Chicago Bulls,PF,6/21/88,12900000\nSviatoslav Mykhailiuk,Detroit Pistons,SF,6/10/97,1416852\nIan Mahinmi,Washington Wizards,C,11/5/86,15450051\nDeonte Burton,Oklahoma City Thunder,SG,1/31/94,1416852\nMarkelle Fultz,Orlando Magic,PG,5/29/98,9745200\nAaron Gordon,Orlando Magic,PF,9/16/95,19863636\nDzanan Musa,Brooklyn Nets,SF,5/8/99,1911600\nPatrick McCaw,Toronto Raptors,SF,10/25/95,4000000\nBismack Biyombo,Charlotte Hornets,C,8/28/92,17000000\nJaVale McGee,Los Angeles Lakers,C,1/19/88,4000000\nJuwan Morgan,Utah Jazz,F,4/17/97,796806\nMarc Gasol,Toronto Raptors,C,1/29/85,25595700\nMarcus Smart,Boston Celtics,PG,3/6/94,12553571\nRudy Gobert,Utah Jazz,C,6/26/92,24258427\nWesley Iwundu,Orlando Magic,SF,12/20/94,1618520\nDwight Powell,Dallas Mavericks,C,7/20/91,10259375\nGoran Dragic,Miami Heat,PG,5/6/86,19217900\nTheo Pinson,Brooklyn Nets,SG,11/5/95,1445697\nDanilo Gallinari,Oklahoma City Thunder,PF,8/8/88,22615559\nJoe Ingles,Utah Jazz,PF,10/2/87,11454546\nJarrett Culver,Minnesota Timberwolves,SG,2/20/99,5813640\nRobert Covington,Minnesota Timberwolves,PF,12/14/90,11301219\nDamyean Dotson,New York Knicks,SG,5/6/94,1618520\nPatrick Beverley,Los Angeles Clippers,PG,7/12/88,12345680\nKevin Love,Cleveland Cavaliers,C,9/7/88,28942830\nQuinn Cook,Los Angeles Lakers,PG,3/23/93,3000000\nJustin Wright-Foreman,Utah Jazz,G,10/27/97,79568\nNoah Vonleh,Minnesota Timberwolves,C,8/24/95,2000000\nTyus Jones,Memphis Grizzlies,PG,5/10/96,9258000\nDewayne Dedmon,Sacramento Kings,C,8/12/89,13333334\nMalcolm Brogdon,Indiana Pacers,PG,12/11/92,20000000\nBen McLemore,Houston Rockets,SG,2/11/93,2028594\nWilson Chandler,Brooklyn Nets,PF,5/10/87,2564753\nIsaac Bonga,Washington Wizards,PG,11/8/99,1416852\nAdam Mokoka,Chicago Bulls,G,7/18/98,79568\nLonzo Ball,New Orleans Pelicans,PG,10/27/97,8719320\nJalen Brunson,Dallas Mavericks,PG,8/31/96,1416852\nJohn Collins,Atlanta Hawks,PF,9/23/97,2686560\nMarvin Williams,Charlotte Hornets,PF,6/19/86,15006250\nBrad Wanamaker,Boston Celtics,PG,7/25/89,1445697\nDonte DiVincenzo,Milwaukee Bucks,SG,1/31/97,2905800\nOmari Spellman,Golden State Warriors,PF,7/21/97,1897800\nJoe Harris,Brooklyn Nets,SF,9/6/91,7666667\nRoyce O'Neale,Utah Jazz,PF,6/5/93,1618520\nDeandre Ayton,Phoenix Suns,C,7/23/98,9562920\nCory Joseph,Sacramento Kings,PG,8/20/91,12000000\nMalcolm Miller,Toronto Raptors,SF,3/6/93,1588231\nJustise Winslow,Miami Heat,PF,3/26/96,13000000\nKevin Durant,Brooklyn Nets,PF,9/29/88,37199000\nEvan Fournier,Orlando Magic,SF,10/29/92,17000000\nChris Silva,Miami Heat,PF,9/19/96,79568\nVince Carter,Atlanta Hawks,PF,1/26/77,2564753\nCody Zeller,Charlotte Hornets,C,10/5/92,14471910\nBrian Bowen,Indiana Pacers,SG,10/2/98,79568\nAaron Holiday,Indiana Pacers,PG,9/30/96,2239200\nTroy Daniels,Los Angeles Lakers,SG,7/15/91,2028594\nBuddy Hield,Sacramento Kings,SG,12/17/92,4861207\nTerance Mann,Los Angeles Clippers,SG,10/18/96,1000000\nJohn Konchar,Memphis Grizzlies,SG,3/22/96,79568\nKZ Okpala,Miami Heat,SF,4/28/99,898310\nDenzel Valentine,Chicago Bulls,SF,11/16/93,3377568\nMarquese Chriss,Golden State Warriors,PF,7/2/97,1678854\nAnthony Davis,Los Angeles Lakers,C,3/11/93,27093019\nNemanja Bjelica,Sacramento Kings,PF,5/9/88,6825000\nChandler Parsons,Atlanta Hawks,SF,10/25/88,25102512\nCourtney Lee,Dallas Mavericks,SG,10/3/85,12759670\nMyles Turner,Indiana Pacers,C,3/24/96,18000000\nKyle O'Quinn,Philadelphia 76ers,C,3/26/90,2174318\nBryn Forbes,San Antonio Spurs,SG,7/23/93,2875000\nDuncan Robinson,Miami Heat,PF,4/22/94,1416852\nDevin Booker,Phoenix Suns,SG,10/30/96,27285000\nGrant Williams,Boston Celtics,PF,11/30/98,2379840\nDeMarcus Cousins,Los Angeles Lakers,C,8/13/90,3500000\nDeMar DeRozan,San Antonio Spurs,SF,8/7/89,27739975\nKristaps Porzingis,Dallas Mavericks,PF,8/2/95,27285000\nBrandon Knight,Cleveland Cavaliers,PG,12/2/91,15643750\nThabo Sefolosha,Houston Rockets,PF,5/2/84,2564753\nDavid Nwaba,Brooklyn Nets,SF,1/14/93,1678854\nQuinndary Weatherspoon,San Antonio Spurs,G,9/10/96,79568\nDewan Hernandez,Toronto Raptors,C,12/9/96,898310\nIsaiah Thomas,Washington Wizards,PG,2/7/89,2320044\nBruce Brown,Detroit Pistons,SG,8/15/96,1416852\nKeldon Johnson,San Antonio Spurs,SF,10/11/99,1950600\nDamian Jones,Atlanta Hawks,C,6/30/95,2305057\nLuguentz Dort,Oklahoma City Thunder,G,4/19/99,79568\nTerence Davis,Toronto Raptors,SG,5/16/97,898310\nChandler Hutchison,Chicago Bulls,SF,4/26/96,2332320\nSteven Adams,Oklahoma City Thunder,C,7/20/93,25842697\nJordan Poole,Golden State Warriors,SG,6/19/99,1964760\nSekou Doumbouya,Detroit Pistons,SF,12/23/00,3285120\nZion Williamson,New Orleans Pelicans,F,7/6/00,9757440\nMike Muscala,Oklahoma City Thunder,C,7/1/91,2028594\nSkal Labissiere,Portland Trail Blazers,C,3/18/96,2338846\nMeyers Leonard,Miami Heat,C,2/27/92,11286515\nReggie Jackson,Detroit Pistons,PG,4/16/90,18086956\nAlfonzo McKinnie,Cleveland Cavaliers,SF,9/17/92,1588231\nYuta Watanabe,Memphis Grizzlies,SF,10/13/94,79568\nKentavious Caldwell-Pope,Los Angeles Lakers,SG,2/18/93,8089282\nKelan Martin,Minnesota Timberwolves,SF,8/3/95,79568\nOG Anunoby,Toronto Raptors,SF,7/17/97,2281800\nTyler Herro,Miami Heat,SG,1/20/00,3640200\nRichaun Holmes,Sacramento Kings,C,10/15/93,4767000\nTyson Chandler,Houston Rockets,C,10/2/82,2564753\nSolomon Hill,Memphis Grizzlies,SF,3/18/91,13290395\nKeita Bates-Diop,Minnesota Timberwolves,SF,1/23/96,1416852\nKelly Olynyk,Miami Heat,C,4/19/91,12667885\nJaxson Hayes,New Orleans Pelicans,C,5/23/00,4862040\nCJ McCollum,Portland Trail Blazers,SG,9/19/91,27556959\nDarius Miller,New Orleans Pelicans,SF,3/21/90,7250000\nLuka Doncic,Dallas Mavericks,PG,2/28/99,7683360\nDeMarre Carroll,San Antonio Spurs,PF,7/27/86,7000000\nCristiano Felicio,Chicago Bulls,C,7/7/92,8156500\nZach LaVine,Chicago Bulls,PG,3/10/95,19500000\nTremont Waters,Boston Celtics,PG,1/10/98,79568\nDejounte Murray,San Antonio Spurs,PG,9/19/96,2321735\nJerome Robinson,Los Angeles Clippers,SG,2/22/97,3567720\nRudy Gay,San Antonio Spurs,PF,8/17/86,14500000\nRyan Broekhoff,Dallas Mavericks,SG,8/23/90,1416852\nJake Layman,Minnesota Timberwolves,PF,3/7/94,3581986\nCameron Johnson,Phoenix Suns,PF,3/3/96,4033440\nAllen Crabbe,Atlanta Hawks,SG,4/9/92,18500000\nJustin James,Sacramento Kings,SG,1/24/97,898310\nEmmanuel Mudiay,Utah Jazz,PG,3/5/96,1737145\nAvery Bradley,Los Angeles Lakers,PG,11/26/90,6767000\nVictor Oladipo,Indiana Pacers,PG,5/4/92,21000000\nCaleb Martin,Charlotte Hornets,SF,9/28/95,898310\nCoby White,Chicago Bulls,SG,2/16/00,5307120\nIsaiah Hartenstein,Houston Rockets,C,5/5/98,1416852\nWill Barton,Denver Nuggets,SF,1/6/91,12776786\nDwayne Bacon,Charlotte Hornets,SG,8/30/95,1618520\nHarrison Barnes,Sacramento Kings,PF,5/30/92,24147727\nTim Frazier,Detroit Pistons,PG,11/1/90,1620564\nJimmy Butler,Miami Heat,SF,9/14/89,32742000\nGary Harris,Denver Nuggets,SG,9/14/94,17839286\nThon Maker,Detroit Pistons,C,2/25/97,3569643\nShai Gilgeous-Alexander,Oklahoma City Thunder,PG,7/12/98,3952920\nHassan Whiteside,Portland Trail Blazers,C,6/13/89,27093018\nKarl-Anthony Towns,Minnesota Timberwolves,C,11/15/95,27285000\nKy Bowman,Golden State Warriors,PG,6/16/97,79568\nBen Simmons,Philadelphia 76ers,PG,7/20/96,8113929\nTerrence Ross,Orlando Magic,SF,2/5/91,12500000\nJordan McLaughlin,Minnesota Timberwolves,PG,4/9/96,79568\nDaniel Theis,Boston Celtics,C,4/4/92,5000000\nJonathan Isaac,Orlando Magic,PF,10/3/97,5806440\nCheick Diallo,Phoenix Suns,C,9/13/96,1678854\nSerge Ibaka,Toronto Raptors,C,9/18/89,23271604\nAmile Jefferson,Orlando Magic,PF,5/7/93,1339515\nCam Reddish,Atlanta Hawks,SF,9/1/99,4245720\nDe'Anthony Melton,Memphis Grizzlies,PG,5/28/98,1416852\nUdonis Haslem,Miami Heat,C,6/9/80,2564753\nCharlie Brown,Atlanta Hawks,SG,2/2/97,79568\nElie Okobo,Phoenix Suns,PG,10/23/97,1416852\nGordon Hayward,Boston Celtics,PF,3/23/90,32700690\nMarco Belinelli,San Antonio Spurs,SF,3/25/86,5846154\nJavonte Green,Boston Celtics,SF,7/23/93,898310\nRondae Hollis-Jefferson,Toronto Raptors,SF,1/3/95,2500000\nCarmelo Anthony,Portland Trail Blazers,PF,5/29/84,2159029\nDanny Green,Los Angeles Lakers,SG,6/22/87,14634147\nStephen Curry,Golden State Warriors,PG,3/14/88,40231758\nEric Paschall,Golden State Warriors,PF,11/4/96,898310\nDaniel Gafford,Chicago Bulls,C,10/1/98,898310\nAnfernee Simons,Portland Trail Blazers,SG,6/8/99,2149560\nFrank Kaminsky,Phoenix Suns,C,4/4/93,4767000\nLuke Kennard,Detroit Pistons,SG,6/24/96,3827160\nJosh Okogie,Minnesota Timberwolves,SG,9/1/98,2530680\nRodney Hood,Portland Trail Blazers,SF,10/20/92,5718000\nDe'Andre Hunter,Atlanta Hawks,SF,12/2/97,7068360\nKlay Thompson,Golden State Warriors,SG,2/8/90,32742000\nJrue Holiday,New Orleans Pelicans,PG,6/12/90,26131111\nPJ Dozier,Denver Nuggets,PG,10/25/96,79568\nAndre Drummond,Detroit Pistons,C,8/10/93,27093018\nJared Harper,Phoenix Suns,PG,9/14/97,79568\nRussell Westbrook,Houston Rockets,PG,11/12/88,38506482\nTony Bradley,Utah Jazz,C,1/8/98,1962360\nOshae Brissett,Toronto Raptors,SF,6/20/98,79568\nGary Clark,Houston Rockets,PF,11/16/94,1416852\nPascal Siakam,Toronto Raptors,PF,4/2/94,2351838\nEric Bledsoe,Milwaukee Bucks,PG,12/9/89,15625000\nTomas Satoransky,Chicago Bulls,PG,10/30/91,10000000\nDavis Bertans,Washington Wizards,PF,11/12/92,7000000\nAmir Coffey,Los Angeles Clippers,G,6/17/97,79568\nIgnas Brazdeikis,New York Knicks,SF,1/8/99,898310\nIvan Rabb,New York Knicks,PF,2/4/97,79568\nKhris Middleton,Milwaukee Bucks,SF,8/12/91,30603448\nKevin Knox,New York Knicks,PF,8/11/99,4380120\nJeff Green,Utah Jazz,PF,8/28/86,2564753\nErsan Ilyasova,Milwaukee Bucks,PF,5/15/87,7000000\nCaleb Swanigan,Sacramento Kings,PF,4/18/97,2033160\nAl Horford,Philadelphia 76ers,C,6/3/86,28000000\nClint Capela,Houston Rockets,C,5/18/94,16896552\nGeorges Niang,Utah Jazz,PF,6/17/93,1645357\nWesley Matthews,Milwaukee Bucks,SF,10/14/86,2564753\nRajon Rondo,Los Angeles Lakers,PG,2/22/86,2564753\nDelon Wright,Dallas Mavericks,PG,4/26/92,9473684\nJa Morant,Memphis Grizzlies,PG,8/10/99,8730240\nFred VanVleet,Toronto Raptors,PG,2/25/94,9346153\nBrandon Clarke,Memphis Grizzlies,PF,9/19/96,2478840\nMiye Oni,Utah Jazz,SG,8/4/97,898310\nJulius Randle,New York Knicks,C,11/29/94,18000000\nGlenn Robinson III,Golden State Warriors,SF,1/8/94,1882867\nDillon Brooks,Memphis Grizzlies,SF,1/22/96,1618520\nZylan Cheatham,New Orleans Pelicans,SF,11/17/95,79568\nMarkieff Morris,Detroit Pistons,PF,9/2/89,3200000\nMalik Beasley,Denver Nuggets,SG,11/26/96,2731713\nJohn Wall,Washington Wizards,PG,9/6/90,38199000\nVlatko Cancar,Denver Nuggets,SF,4/10/97,898310\nAlize Johnson,Indiana Pacers,PF,4/22/96,1416852\nAndrew Wiggins,Minnesota Timberwolves,SF,2/23/95,27504630\nKhyri Thomas,Detroit Pistons,SG,5/8/96,1416852\nMitchell Robinson,New York Knicks,C,4/1/98,1559712\nDamian Lillard,Portland Trail Blazers,PG,7/15/90,29802321\nNassir Little,Portland Trail Blazers,PF,2/11/00,2105520\nMikal Bridges,Phoenix Suns,SF,8/30/96,4161000\nKyle Anderson,Memphis Grizzlies,PF,9/20/93,9073050\nGarrett Temple,Brooklyn Nets,PG,5/8/86,4767000\nKyle Korver,Milwaukee Bucks,PF,3/17/81,6004753\nAl-Farouq Aminu,Orlando Magic,PF,9/21/90,9258000\nJames Harden,Houston Rockets,PG,8/26/89,38199000\nDerrick White,San Antonio Spurs,PG,7/2/94,1948080\nJaKarr Sampson,Indiana Pacers,SF,3/20/93,1737145\nDario Saric,Phoenix Suns,PF,4/8/94,3481985\nIvica Zubac,Los Angeles Clippers,C,3/18/97,6481482\nJuan Hernangomez,Denver Nuggets,PF,9/28/95,3321029\nJarrell Brantley,Utah Jazz,PF,6/7/96,79568\nEric Gordon,Houston Rockets,PG,12/25/88,14057730\nNaz Reid,Minnesota Timberwolves,F,8/26/99,898310\nJustin Robinson,Washington Wizards,PG,10/12/97,898310\nGrayson Allen,Memphis Grizzlies,SG,10/8/95,2429400\nTrevor Ariza,Sacramento Kings,SF,6/30/85,12200000\nBrandon Goodwin,Atlanta Hawks,PG,10/2/95,79568\nE'Twaun Moore,New Orleans Pelicans,PG,2/25/89,8664928\nMario Hezonja,Portland Trail Blazers,PF,2/25/95,1737145\nHenry Ellenson,Brooklyn Nets,PF,1/13/97,79568\nJohnathan Motley,Los Angeles Clippers,PF,5/4/95,79568\nJames Ennis,Philadelphia 76ers,SF,7/1/90,1882867\nAndre Roberson,Oklahoma City Thunder,SF,12/4/91,10740740\nGarrison Mathews,Washington Wizards,SG,10/24/96,79568\nJahlil Okafor,New Orleans Pelicans,C,12/15/95,1702486\nMfiondu Kabengele,Los Angeles Clippers,C,8/14/97,1977000\nTreveon Graham,Minnesota Timberwolves,SG,10/28/93,1645357\nSeth Curry,Dallas Mavericks,PG,8/23/90,7461380\nD'Angelo Russell,Golden State Warriors,PG,2/23/96,27285000\nJustin Holiday,Indiana Pacers,SG,4/5/89,4767000\nTyrone Wallace,Atlanta Hawks,PG,6/10/94,1620564\nMiles Bridges,Charlotte Hornets,SF,3/21/98,3755400\nBogdan Bogdanovic,Sacramento Kings,SG,8/18/92,8529386\nMatt Thomas,Toronto Raptors,SG,8/4/94,898310\nJordan Bell,Minnesota Timberwolves,C,1/7/95,1620564\nWenyen Gabriel,Sacramento Kings,PF,3/26/97,79568\nTony Snell,Detroit Pistons,SF,11/10/91,11392857\nShaquille Harrison,Chicago Bulls,PG,10/6/93,1620564\nYogi Ferrell,Sacramento Kings,PG,5/9/93,3150000\nMike Scott,Philadelphia 76ers,PF,7/16/88,4767000\nJarred Vanderbilt,Denver Nuggets,PF,4/3/99,1416852\nJeff Teague,Minnesota Timberwolves,PG,6/10/88,19000000\nZach Norvell,Los Angeles Lakers,SG,12/9/97,79568\nMaxi Kleber,Dallas Mavericks,C,1/29/92,8000000\nMatisse Thybulle,Philadelphia 76ers,SG,3/4/97,2582160\nRyan Arcidiacono,Chicago Bulls,PG,3/26/94,3000000\nWayne Ellington,New York Knicks,SG,11/29/87,8000000\nKawhi Leonard,Los Angeles Clippers,SF,6/29/91,32742000\nMontrezl Harrell,Los Angeles Clippers,C,1/26/94,6000000\nJusuf Nurkic,Portland Trail Blazers,C,8/23/94,12000000\nMatthew Dellavedova,Cleveland Cavaliers,PG,9/8/90,9607500\nCody Martin,Charlotte Hornets,SF,9/28/95,1173310\nZhaire Smith,Philadelphia 76ers,SG,6/4/99,3058800\nRJ Barrett,New York Knicks,SG,6/14/00,7839960\nLonnie Walker,San Antonio Spurs,SG,12/14/98,2764200\nTaurean Prince,Brooklyn Nets,SF,3/22/94,3481985\nElfrid Payton,New York Knicks,PG,2/22/94,8000000\nBlake Griffin,Detroit Pistons,PF,3/16/89,34449964\nMarko Guduric,Memphis Grizzlies,SG,3/8/95,2625000\nZach Collins,Portland Trail Blazers,C,11/19/97,4240200\nStanley Johnson,Toronto Raptors,PF,5/29/96,3623000\nBoban Marjanovic,Dallas Mavericks,C,8/15/88,3500000\nJosh Magette,Orlando Magic,PG,11/28/89,79568\nKyle Lowry,Toronto Raptors,PG,3/25/86,33296296\nDarius Garland,Cleveland Cavaliers,PG,1/26/00,6400920\nFrank Jackson,New Orleans Pelicans,PG,5/4/98,1618520\nDragan Bender,Milwaukee Bucks,PF,11/17/97,1678854\nKenrich Williams,New Orleans Pelicans,PF,12/2/94,1416852\nJerami Grant,Denver Nuggets,PF,3/12/94,9346153\nAllonzo Trier,New York Knicks,PG,1/17/96,3551100\nPat Connaughton,Milwaukee Bucks,SG,1/6/93,1723050\nDomantas Sabonis,Indiana Pacers,C,5/3/96,3529554\nDylan Windler,Cleveland Cavaliers,GF,9/22/96,2035800\nAntonius Cleveland,Dallas Mavericks,SG,2/2/94,79568\nDamion Lee,Golden State Warriors,SG,10/21/92,79568\nKhem Birch,Orlando Magic,C,9/28/92,3000000\nAron Baynes,Phoenix Suns,C,12/9/86,5453280\nKemba Walker,Boston Celtics,PG,5/8/90,32742000\nNerlens Noel,Oklahoma City Thunder,C,4/10/94,1882867\nJabari Parker,Atlanta Hawks,PF,3/15/95,6500000\nCarsen Edwards,Boston Celtics,SG,3/12/98,1228026\nAnthony Tolliver,Portland Trail Blazers,PF,6/1/85,2564753\nLauri Markkanen,Chicago Bulls,PF,5/22/97,5300400\nKris Dunn,Chicago Bulls,PG,3/18/94,5348007\nReggie Bullock,New York Knicks,SF,3/16/91,4000000\nMike Conley,Utah Jazz,PG,10/11/87,32511623\nJaylen Nowell,Minnesota Timberwolves,SG,7/9/99,1400000\nGorgui Dieng,Minnesota Timberwolves,C,1/18/90,16229213\nPatrick Patterson,Los Angeles Clippers,PF,3/14/89,3068660\nJarrett Allen,Brooklyn Nets,C,4/21/98,2376840\nBobby Portis,New York Knicks,C,2/10/95,15000000\nJoel Embiid,Philadelphia 76ers,C,3/16/94,27504630\nJonas Valanciunas,Memphis Grizzlies,C,5/6/92,16000000\nChris Chiozza,Washington Wizards,PG,11/21/95,79568\nKent Bazemore,Portland Trail Blazers,SF,7/1/89,19269663\nTristan Thompson,Cleveland Cavaliers,C,3/13/91,18539130\nMason Plumlee,Denver Nuggets,C,3/5/90,14041096\nShabazz Napier,Minnesota Timberwolves,PG,7/14/91,1845301\nEdmond Sumner,Indiana Pacers,PG,12/31/95,2000000\nAlex Len,Atlanta Hawks,C,6/16/93,4160000\nJosh Richardson,Philadelphia 76ers,SF,9/15/93,10116576\nBojan Bogdanovic,Utah Jazz,SF,4/18/89,17000000\nIman Shumpert,Brooklyn Nets,PG,6/26/90,2031676\nDaryl Macon,Miami Heat,SG,11/29/95,79568\nRodney McGruder,Los Angeles Clippers,SG,7/29/91,4807693\nBam Adebayo,Miami Heat,C,7/18/97,3454080\nJacob Evans,Golden State Warriors,SG,6/18/97,1928280\nNigel Williams-Goss,Utah Jazz,PG,9/16/94,1500000\nTerrance Ferguson,Oklahoma City Thunder,SF,5/17/98,2475840\nMichael Carter-Williams,Orlando Magic,PG,10/10/91,2028594\nBol Bol,Denver Nuggets,C,11/16/99,79568\nWillie Cauley-Stein,Golden State Warriors,C,8/18/93,2177483\nNikola Vucevic,Orlando Magic,C,10/24/90,28000000\nNicolas Batum,Charlotte Hornets,SF,12/14/88,25565217\nKyrie Irving,Brooklyn Nets,PG,3/23/92,31742000\nJeremy Lamb,Indiana Pacers,SF,5/30/92,10500000\nDonovan Mitchell,Utah Jazz,SG,9/7/96,3635760\nThanasis Antetokounmpo,Milwaukee Bucks,SF,7/18/92,1445697\nJames Johnson,Miami Heat,PF,2/20/87,15349400\nMonte Morris,Denver Nuggets,PG,6/27/95,1588231\nTerry Rozier,Charlotte Hornets,PG,3/17/94,19894737\nDeAndre Jordan,Brooklyn Nets,C,7/21/88,9881598\nJae Crowder,Memphis Grizzlies,SF,7/6/90,7815533\nJosh Gray,New Orleans Pelicans,PG,9/9/93,79568\nGoga Bitadze,Indiana Pacers,C,7/20/99,2816760\nKobi Simmons,Charlotte Hornets,PG,7/4/97,79568\nDerrick Favors,New Orleans Pelicans,C,7/15/91,17650000\nLandry Shamet,Los Angeles Clippers,SG,3/13/97,1995120\nJalen McDaniels,Charlotte Hornets,PF,1/31/98,898310\nBruno Caboclo,Memphis Grizzlies,SF,9/21/95,1845301\nDrew Eubanks,San Antonio Spurs,PF,2/1/97,79568\nRaul Neto,Philadelphia

In [43]:
# Seek to the start of file (index 0)
myfile.seek(0)

0

In [44]:
# Now read again
myfile.read()

"Name,Team,Position,Birthday,Salary\nShake Milton,Philadelphia 76ers,SG,9/26/96,1445697\nChristian Wood,Detroit Pistons,PF,9/27/95,1645357\nPJ Washington,Charlotte Hornets,PF,8/23/98,3831840\nDerrick Rose,Detroit Pistons,PG,10/4/88,7317074\nMarial Shayok,Philadelphia 76ers,G,7/26/95,79568\nDraymond Green,Golden State Warriors,PF,3/4/90,18539130\nKendrick Nunn,Miami Heat,SG,8/3/95,1416852\nCedi Osman,Cleveland Cavaliers,SF,4/8/95,2907143\nBrook Lopez,Milwaukee Bucks,C,4/1/88,12093024\nTorrey Craig,Denver Nuggets,SF,12/19/90,2000000\nJordan Clarkson,Cleveland Cavaliers,PG,6/7/92,13437500\nAlex Caruso,Los Angeles Lakers,PG,2/28/94,2750000\nNorvel Pelle,Philadelphia 76ers,FC,2/3/93,79568\nTyler Johnson,Phoenix Suns,PG,5/7/92,19245370\nAlec Burks,Golden State Warriors,SG,7/20/91,2320044\nJaMychal Green,Los Angeles Clippers,PF,6/21/90,4767000\nDwight Howard,Los Angeles Lakers,C,12/8/85,5603850\nNikola Jokic,Denver Nuggets,C,2/19/95,27504630\nChris Boucher,Toronto Raptors,PF,1/11/93,1588231\nMarcus Morris,New York Knicks,PF,9/2/89,15000000\nKevin Huerter,Atlanta Hawks,SG,8/27/98,2636280\nRui Hachimura,Washington Wizards,PF,2/8/98,4469160\nGeorge Hill,Milwaukee Bucks,PG,5/4/86,10133907\nNickeil Alexander-Walker,New Orleans Pelicans,SG,9/2/98,2964840\nJaylen Hoard,Portland Trail Blazers,SF,3/30/99,79568\nTyler Cook,Cleveland Cavaliers,PF,9/23/97,79568\nOtto Porter,Chicago Bulls,SF,6/3/93,27250576\nLangston Galloway,Detroit Pistons,PG,12/9/91,7333333\nEvan Turner,Atlanta Hawks,PG,10/27/88,18606556\nNorman Powell,Toronto Raptors,SG,5/25/93,10116576\nNicolas Claxton,Brooklyn Nets,PF,4/17/99,898310\nMichael Frazier,Houston Rockets,G,3/8/94,79568\nPaul Millsap,Denver Nuggets,PF,2/10/85,30000000\nFurkan Korkmaz,Philadelphia 76ers,SG,7/24/97,1620564\nTrey Burke,Philadelphia 76ers,PG,11/12/92,2028594\nBradley Beal,Washington Wizards,SG,6/28/93,27093018\nThomas Bryant,Washington Wizards,C,7/31/97,8000000\nDean Wade,Cleveland Cavaliers,PF,11/20/96,79568\nChris Paul,Oklahoma City Thunder,PG,5/6/85,38506482\nJosh Hart,New Orleans Pelicans,SF,3/6/95,1934160\nLaMarcus Aldridge,San Antonio Spurs,C,7/19/85,26000000\nDaQuan Jeffries,Sacramento Kings,SG,8/30/97,898310\nHamidou Diallo,Oklahoma City Thunder,SF,7/31/98,1416852\nJamal Murray,Denver Nuggets,PG,2/23/97,4444746\nDarius Bazley,Oklahoma City Thunder,PF,6/12/00,2284800\nRobert Franks,Charlotte Hornets,F,12/18/96,79568\nGerald Green,Houston Rockets,SF,1/26/86,2564753\nThaddeus Young,Chicago Bulls,PF,6/21/88,12900000\nSviatoslav Mykhailiuk,Detroit Pistons,SF,6/10/97,1416852\nIan Mahinmi,Washington Wizards,C,11/5/86,15450051\nDeonte Burton,Oklahoma City Thunder,SG,1/31/94,1416852\nMarkelle Fultz,Orlando Magic,PG,5/29/98,9745200\nAaron Gordon,Orlando Magic,PF,9/16/95,19863636\nDzanan Musa,Brooklyn Nets,SF,5/8/99,1911600\nPatrick McCaw,Toronto Raptors,SF,10/25/95,4000000\nBismack Biyombo,Charlotte Hornets,C,8/28/92,17000000\nJaVale McGee,Los Angeles Lakers,C,1/19/88,4000000\nJuwan Morgan,Utah Jazz,F,4/17/97,796806\nMarc Gasol,Toronto Raptors,C,1/29/85,25595700\nMarcus Smart,Boston Celtics,PG,3/6/94,12553571\nRudy Gobert,Utah Jazz,C,6/26/92,24258427\nWesley Iwundu,Orlando Magic,SF,12/20/94,1618520\nDwight Powell,Dallas Mavericks,C,7/20/91,10259375\nGoran Dragic,Miami Heat,PG,5/6/86,19217900\nTheo Pinson,Brooklyn Nets,SG,11/5/95,1445697\nDanilo Gallinari,Oklahoma City Thunder,PF,8/8/88,22615559\nJoe Ingles,Utah Jazz,PF,10/2/87,11454546\nJarrett Culver,Minnesota Timberwolves,SG,2/20/99,5813640\nRobert Covington,Minnesota Timberwolves,PF,12/14/90,11301219\nDamyean Dotson,New York Knicks,SG,5/6/94,1618520\nPatrick Beverley,Los Angeles Clippers,PG,7/12/88,12345680\nKevin Love,Cleveland Cavaliers,C,9/7/88,28942830\nQuinn Cook,Los Angeles Lakers,PG,3/23/93,3000000\nJustin Wright-Foreman,Utah Jazz,G,10/27/97,79568\nNoah Vonleh,Minnesota Timberwolves,C,8/24/95,2000000\nTyus Jones,Memphis Grizzlies,PG,5/10/96,9258000\nDewayne Dedmon,Sacramento Kings,C,8/12/89,13333334\nMalcolm Brogdon,Indiana Pacers,PG,12/11/92,20000000\nBen McLemore,Houston Rockets,SG,2/11/93,2028594\nWilson Chandler,Brooklyn Nets,PF,5/10/87,2564753\nIsaac Bonga,Washington Wizards,PG,11/8/99,1416852\nAdam Mokoka,Chicago Bulls,G,7/18/98,79568\nLonzo Ball,New Orleans Pelicans,PG,10/27/97,8719320\nJalen Brunson,Dallas Mavericks,PG,8/31/96,1416852\nJohn Collins,Atlanta Hawks,PF,9/23/97,2686560\nMarvin Williams,Charlotte Hornets,PF,6/19/86,15006250\nBrad Wanamaker,Boston Celtics,PG,7/25/89,1445697\nDonte DiVincenzo,Milwaukee Bucks,SG,1/31/97,2905800\nOmari Spellman,Golden State Warriors,PF,7/21/97,1897800\nJoe Harris,Brooklyn Nets,SF,9/6/91,7666667\nRoyce O'Neale,Utah Jazz,PF,6/5/93,1618520\nDeandre Ayton,Phoenix Suns,C,7/23/98,9562920\nCory Joseph,Sacramento Kings,PG,8/20/91,12000000\nMalcolm Miller,Toronto Raptors,SF,3/6/93,1588231\nJustise Winslow,Miami Heat,PF,3/26/96,13000000\nKevin Durant,Brooklyn Nets,PF,9/29/88,37199000\nEvan Fournier,Orlando Magic,SF,10/29/92,17000000\nChris Silva,Miami Heat,PF,9/19/96,79568\nVince Carter,Atlanta Hawks,PF,1/26/77,2564753\nCody Zeller,Charlotte Hornets,C,10/5/92,14471910\nBrian Bowen,Indiana Pacers,SG,10/2/98,79568\nAaron Holiday,Indiana Pacers,PG,9/30/96,2239200\nTroy Daniels,Los Angeles Lakers,SG,7/15/91,2028594\nBuddy Hield,Sacramento Kings,SG,12/17/92,4861207\nTerance Mann,Los Angeles Clippers,SG,10/18/96,1000000\nJohn Konchar,Memphis Grizzlies,SG,3/22/96,79568\nKZ Okpala,Miami Heat,SF,4/28/99,898310\nDenzel Valentine,Chicago Bulls,SF,11/16/93,3377568\nMarquese Chriss,Golden State Warriors,PF,7/2/97,1678854\nAnthony Davis,Los Angeles Lakers,C,3/11/93,27093019\nNemanja Bjelica,Sacramento Kings,PF,5/9/88,6825000\nChandler Parsons,Atlanta Hawks,SF,10/25/88,25102512\nCourtney Lee,Dallas Mavericks,SG,10/3/85,12759670\nMyles Turner,Indiana Pacers,C,3/24/96,18000000\nKyle O'Quinn,Philadelphia 76ers,C,3/26/90,2174318\nBryn Forbes,San Antonio Spurs,SG,7/23/93,2875000\nDuncan Robinson,Miami Heat,PF,4/22/94,1416852\nDevin Booker,Phoenix Suns,SG,10/30/96,27285000\nGrant Williams,Boston Celtics,PF,11/30/98,2379840\nDeMarcus Cousins,Los Angeles Lakers,C,8/13/90,3500000\nDeMar DeRozan,San Antonio Spurs,SF,8/7/89,27739975\nKristaps Porzingis,Dallas Mavericks,PF,8/2/95,27285000\nBrandon Knight,Cleveland Cavaliers,PG,12/2/91,15643750\nThabo Sefolosha,Houston Rockets,PF,5/2/84,2564753\nDavid Nwaba,Brooklyn Nets,SF,1/14/93,1678854\nQuinndary Weatherspoon,San Antonio Spurs,G,9/10/96,79568\nDewan Hernandez,Toronto Raptors,C,12/9/96,898310\nIsaiah Thomas,Washington Wizards,PG,2/7/89,2320044\nBruce Brown,Detroit Pistons,SG,8/15/96,1416852\nKeldon Johnson,San Antonio Spurs,SF,10/11/99,1950600\nDamian Jones,Atlanta Hawks,C,6/30/95,2305057\nLuguentz Dort,Oklahoma City Thunder,G,4/19/99,79568\nTerence Davis,Toronto Raptors,SG,5/16/97,898310\nChandler Hutchison,Chicago Bulls,SF,4/26/96,2332320\nSteven Adams,Oklahoma City Thunder,C,7/20/93,25842697\nJordan Poole,Golden State Warriors,SG,6/19/99,1964760\nSekou Doumbouya,Detroit Pistons,SF,12/23/00,3285120\nZion Williamson,New Orleans Pelicans,F,7/6/00,9757440\nMike Muscala,Oklahoma City Thunder,C,7/1/91,2028594\nSkal Labissiere,Portland Trail Blazers,C,3/18/96,2338846\nMeyers Leonard,Miami Heat,C,2/27/92,11286515\nReggie Jackson,Detroit Pistons,PG,4/16/90,18086956\nAlfonzo McKinnie,Cleveland Cavaliers,SF,9/17/92,1588231\nYuta Watanabe,Memphis Grizzlies,SF,10/13/94,79568\nKentavious Caldwell-Pope,Los Angeles Lakers,SG,2/18/93,8089282\nKelan Martin,Minnesota Timberwolves,SF,8/3/95,79568\nOG Anunoby,Toronto Raptors,SF,7/17/97,2281800\nTyler Herro,Miami Heat,SG,1/20/00,3640200\nRichaun Holmes,Sacramento Kings,C,10/15/93,4767000\nTyson Chandler,Houston Rockets,C,10/2/82,2564753\nSolomon Hill,Memphis Grizzlies,SF,3/18/91,13290395\nKeita Bates-Diop,Minnesota Timberwolves,SF,1/23/96,1416852\nKelly Olynyk,Miami Heat,C,4/19/91,12667885\nJaxson Hayes,New Orleans Pelicans,C,5/23/00,4862040\nCJ McCollum,Portland Trail Blazers,SG,9/19/91,27556959\nDarius Miller,New Orleans Pelicans,SF,3/21/90,7250000\nLuka Doncic,Dallas Mavericks,PG,2/28/99,7683360\nDeMarre Carroll,San Antonio Spurs,PF,7/27/86,7000000\nCristiano Felicio,Chicago Bulls,C,7/7/92,8156500\nZach LaVine,Chicago Bulls,PG,3/10/95,19500000\nTremont Waters,Boston Celtics,PG,1/10/98,79568\nDejounte Murray,San Antonio Spurs,PG,9/19/96,2321735\nJerome Robinson,Los Angeles Clippers,SG,2/22/97,3567720\nRudy Gay,San Antonio Spurs,PF,8/17/86,14500000\nRyan Broekhoff,Dallas Mavericks,SG,8/23/90,1416852\nJake Layman,Minnesota Timberwolves,PF,3/7/94,3581986\nCameron Johnson,Phoenix Suns,PF,3/3/96,4033440\nAllen Crabbe,Atlanta Hawks,SG,4/9/92,18500000\nJustin James,Sacramento Kings,SG,1/24/97,898310\nEmmanuel Mudiay,Utah Jazz,PG,3/5/96,1737145\nAvery Bradley,Los Angeles Lakers,PG,11/26/90,6767000\nVictor Oladipo,Indiana Pacers,PG,5/4/92,21000000\nCaleb Martin,Charlotte Hornets,SF,9/28/95,898310\nCoby White,Chicago Bulls,SG,2/16/00,5307120\nIsaiah Hartenstein,Houston Rockets,C,5/5/98,1416852\nWill Barton,Denver Nuggets,SF,1/6/91,12776786\nDwayne Bacon,Charlotte Hornets,SG,8/30/95,1618520\nHarrison Barnes,Sacramento Kings,PF,5/30/92,24147727\nTim Frazier,Detroit Pistons,PG,11/1/90,1620564\nJimmy Butler,Miami Heat,SF,9/14/89,32742000\nGary Harris,Denver Nuggets,SG,9/14/94,17839286\nThon Maker,Detroit Pistons,C,2/25/97,3569643\nShai Gilgeous-Alexander,Oklahoma City Thunder,PG,7/12/98,3952920\nHassan Whiteside,Portland Trail Blazers,C,6/13/89,27093018\nKarl-Anthony Towns,Minnesota Timberwolves,C,11/15/95,27285000\nKy Bowman,Golden State Warriors,PG,6/16/97,79568\nBen Simmons,Philadelphia 76ers,PG,7/20/96,8113929\nTerrence Ross,Orlando Magic,SF,2/5/91,12500000\nJordan McLaughlin,Minnesota Timberwolves,PG,4/9/96,79568\nDaniel Theis,Boston Celtics,C,4/4/92,5000000\nJonathan Isaac,Orlando Magic,PF,10/3/97,5806440\nCheick Diallo,Phoenix Suns,C,9/13/96,1678854\nSerge Ibaka,Toronto Raptors,C,9/18/89,23271604\nAmile Jefferson,Orlando Magic,PF,5/7/93,1339515\nCam Reddish,Atlanta Hawks,SF,9/1/99,4245720\nDe'Anthony Melton,Memphis Grizzlies,PG,5/28/98,1416852\nUdonis Haslem,Miami Heat,C,6/9/80,2564753\nCharlie Brown,Atlanta Hawks,SG,2/2/97,79568\nElie Okobo,Phoenix Suns,PG,10/23/97,1416852\nGordon Hayward,Boston Celtics,PF,3/23/90,32700690\nMarco Belinelli,San Antonio Spurs,SF,3/25/86,5846154\nJavonte Green,Boston Celtics,SF,7/23/93,898310\nRondae Hollis-Jefferson,Toronto Raptors,SF,1/3/95,2500000\nCarmelo Anthony,Portland Trail Blazers,PF,5/29/84,2159029\nDanny Green,Los Angeles Lakers,SG,6/22/87,14634147\nStephen Curry,Golden State Warriors,PG,3/14/88,40231758\nEric Paschall,Golden State Warriors,PF,11/4/96,898310\nDaniel Gafford,Chicago Bulls,C,10/1/98,898310\nAnfernee Simons,Portland Trail Blazers,SG,6/8/99,2149560\nFrank Kaminsky,Phoenix Suns,C,4/4/93,4767000\nLuke Kennard,Detroit Pistons,SG,6/24/96,3827160\nJosh Okogie,Minnesota Timberwolves,SG,9/1/98,2530680\nRodney Hood,Portland Trail Blazers,SF,10/20/92,5718000\nDe'Andre Hunter,Atlanta Hawks,SF,12/2/97,7068360\nKlay Thompson,Golden State Warriors,SG,2/8/90,32742000\nJrue Holiday,New Orleans Pelicans,PG,6/12/90,26131111\nPJ Dozier,Denver Nuggets,PG,10/25/96,79568\nAndre Drummond,Detroit Pistons,C,8/10/93,27093018\nJared Harper,Phoenix Suns,PG,9/14/97,79568\nRussell Westbrook,Houston Rockets,PG,11/12/88,38506482\nTony Bradley,Utah Jazz,C,1/8/98,1962360\nOshae Brissett,Toronto Raptors,SF,6/20/98,79568\nGary Clark,Houston Rockets,PF,11/16/94,1416852\nPascal Siakam,Toronto Raptors,PF,4/2/94,2351838\nEric Bledsoe,Milwaukee Bucks,PG,12/9/89,15625000\nTomas Satoransky,Chicago Bulls,PG,10/30/91,10000000\nDavis Bertans,Washington Wizards,PF,11/12/92,7000000\nAmir Coffey,Los Angeles Clippers,G,6/17/97,79568\nIgnas Brazdeikis,New York Knicks,SF,1/8/99,898310\nIvan Rabb,New York Knicks,PF,2/4/97,79568\nKhris Middleton,Milwaukee Bucks,SF,8/12/91,30603448\nKevin Knox,New York Knicks,PF,8/11/99,4380120\nJeff Green,Utah Jazz,PF,8/28/86,2564753\nErsan Ilyasova,Milwaukee Bucks,PF,5/15/87,7000000\nCaleb Swanigan,Sacramento Kings,PF,4/18/97,2033160\nAl Horford,Philadelphia 76ers,C,6/3/86,28000000\nClint Capela,Houston Rockets,C,5/18/94,16896552\nGeorges Niang,Utah Jazz,PF,6/17/93,1645357\nWesley Matthews,Milwaukee Bucks,SF,10/14/86,2564753\nRajon Rondo,Los Angeles Lakers,PG,2/22/86,2564753\nDelon Wright,Dallas Mavericks,PG,4/26/92,9473684\nJa Morant,Memphis Grizzlies,PG,8/10/99,8730240\nFred VanVleet,Toronto Raptors,PG,2/25/94,9346153\nBrandon Clarke,Memphis Grizzlies,PF,9/19/96,2478840\nMiye Oni,Utah Jazz,SG,8/4/97,898310\nJulius Randle,New York Knicks,C,11/29/94,18000000\nGlenn Robinson III,Golden State Warriors,SF,1/8/94,1882867\nDillon Brooks,Memphis Grizzlies,SF,1/22/96,1618520\nZylan Cheatham,New Orleans Pelicans,SF,11/17/95,79568\nMarkieff Morris,Detroit Pistons,PF,9/2/89,3200000\nMalik Beasley,Denver Nuggets,SG,11/26/96,2731713\nJohn Wall,Washington Wizards,PG,9/6/90,38199000\nVlatko Cancar,Denver Nuggets,SF,4/10/97,898310\nAlize Johnson,Indiana Pacers,PF,4/22/96,1416852\nAndrew Wiggins,Minnesota Timberwolves,SF,2/23/95,27504630\nKhyri Thomas,Detroit Pistons,SG,5/8/96,1416852\nMitchell Robinson,New York Knicks,C,4/1/98,1559712\nDamian Lillard,Portland Trail Blazers,PG,7/15/90,29802321\nNassir Little,Portland Trail Blazers,PF,2/11/00,2105520\nMikal Bridges,Phoenix Suns,SF,8/30/96,4161000\nKyle Anderson,Memphis Grizzlies,PF,9/20/93,9073050\nGarrett Temple,Brooklyn Nets,PG,5/8/86,4767000\nKyle Korver,Milwaukee Bucks,PF,3/17/81,6004753\nAl-Farouq Aminu,Orlando Magic,PF,9/21/90,9258000\nJames Harden,Houston Rockets,PG,8/26/89,38199000\nDerrick White,San Antonio Spurs,PG,7/2/94,1948080\nJaKarr Sampson,Indiana Pacers,SF,3/20/93,1737145\nDario Saric,Phoenix Suns,PF,4/8/94,3481985\nIvica Zubac,Los Angeles Clippers,C,3/18/97,6481482\nJuan Hernangomez,Denver Nuggets,PF,9/28/95,3321029\nJarrell Brantley,Utah Jazz,PF,6/7/96,79568\nEric Gordon,Houston Rockets,PG,12/25/88,14057730\nNaz Reid,Minnesota Timberwolves,F,8/26/99,898310\nJustin Robinson,Washington Wizards,PG,10/12/97,898310\nGrayson Allen,Memphis Grizzlies,SG,10/8/95,2429400\nTrevor Ariza,Sacramento Kings,SF,6/30/85,12200000\nBrandon Goodwin,Atlanta Hawks,PG,10/2/95,79568\nE'Twaun Moore,New Orleans Pelicans,PG,2/25/89,8664928\nMario Hezonja,Portland Trail Blazers,PF,2/25/95,1737145\nHenry Ellenson,Brooklyn Nets,PF,1/13/97,79568\nJohnathan Motley,Los Angeles Clippers,PF,5/4/95,79568\nJames Ennis,Philadelphia 76ers,SF,7/1/90,1882867\nAndre Roberson,Oklahoma City Thunder,SF,12/4/91,10740740\nGarrison Mathews,Washington Wizards,SG,10/24/96,79568\nJahlil Okafor,New Orleans Pelicans,C,12/15/95,1702486\nMfiondu Kabengele,Los Angeles Clippers,C,8/14/97,1977000\nTreveon Graham,Minnesota Timberwolves,SG,10/28/93,1645357\nSeth Curry,Dallas Mavericks,PG,8/23/90,7461380\nD'Angelo Russell,Golden State Warriors,PG,2/23/96,27285000\nJustin Holiday,Indiana Pacers,SG,4/5/89,4767000\nTyrone Wallace,Atlanta Hawks,PG,6/10/94,1620564\nMiles Bridges,Charlotte Hornets,SF,3/21/98,3755400\nBogdan Bogdanovic,Sacramento Kings,SG,8/18/92,8529386\nMatt Thomas,Toronto Raptors,SG,8/4/94,898310\nJordan Bell,Minnesota Timberwolves,C,1/7/95,1620564\nWenyen Gabriel,Sacramento Kings,PF,3/26/97,79568\nTony Snell,Detroit Pistons,SF,11/10/91,11392857\nShaquille Harrison,Chicago Bulls,PG,10/6/93,1620564\nYogi Ferrell,Sacramento Kings,PG,5/9/93,3150000\nMike Scott,Philadelphia 76ers,PF,7/16/88,4767000\nJarred Vanderbilt,Denver Nuggets,PF,4/3/99,1416852\nJeff Teague,Minnesota Timberwolves,PG,6/10/88,19000000\nZach Norvell,Los Angeles Lakers,SG,12/9/97,79568\nMaxi Kleber,Dallas Mavericks,C,1/29/92,8000000\nMatisse Thybulle,Philadelphia 76ers,SG,3/4/97,2582160\nRyan Arcidiacono,Chicago Bulls,PG,3/26/94,3000000\nWayne Ellington,New York Knicks,SG,11/29/87,8000000\nKawhi Leonard,Los Angeles Clippers,SF,6/29/91,32742000\nMontrezl Harrell,Los Angeles Clippers,C,1/26/94,6000000\nJusuf Nurkic,Portland Trail Blazers,C,8/23/94,12000000\nMatthew Dellavedova,Cleveland Cavaliers,PG,9/8/90,9607500\nCody Martin,Charlotte Hornets,SF,9/28/95,1173310\nZhaire Smith,Philadelphia 76ers,SG,6/4/99,3058800\nRJ Barrett,New York Knicks,SG,6/14/00,7839960\nLonnie Walker,San Antonio Spurs,SG,12/14/98,2764200\nTaurean Prince,Brooklyn Nets,SF,3/22/94,3481985\nElfrid Payton,New York Knicks,PG,2/22/94,8000000\nBlake Griffin,Detroit Pistons,PF,3/16/89,34449964\nMarko Guduric,Memphis Grizzlies,SG,3/8/95,2625000\nZach Collins,Portland Trail Blazers,C,11/19/97,4240200\nStanley Johnson,Toronto Raptors,PF,5/29/96,3623000\nBoban Marjanovic,Dallas Mavericks,C,8/15/88,3500000\nJosh Magette,Orlando Magic,PG,11/28/89,79568\nKyle Lowry,Toronto Raptors,PG,3/25/86,33296296\nDarius Garland,Cleveland Cavaliers,PG,1/26/00,6400920\nFrank Jackson,New Orleans Pelicans,PG,5/4/98,1618520\nDragan Bender,Milwaukee Bucks,PF,11/17/97,1678854\nKenrich Williams,New Orleans Pelicans,PF,12/2/94,1416852\nJerami Grant,Denver Nuggets,PF,3/12/94,9346153\nAllonzo Trier,New York Knicks,PG,1/17/96,3551100\nPat Connaughton,Milwaukee Bucks,SG,1/6/93,1723050\nDomantas Sabonis,Indiana Pacers,C,5/3/96,3529554\nDylan Windler,Cleveland Cavaliers,GF,9/22/96,2035800\nAntonius Cleveland,Dallas Mavericks,SG,2/2/94,79568\nDamion Lee,Golden State Warriors,SG,10/21/92,79568\nKhem Birch,Orlando Magic,C,9/28/92,3000000\nAron Baynes,Phoenix Suns,C,12/9/86,5453280\nKemba Walker,Boston Celtics,PG,5/8/90,32742000\nNerlens Noel,Oklahoma City Thunder,C,4/10/94,1882867\nJabari Parker,Atlanta Hawks,PF,3/15/95,6500000\nCarsen Edwards,Boston Celtics,SG,3/12/98,1228026\nAnthony Tolliver,Portland Trail Blazers,PF,6/1/85,2564753\nLauri Markkanen,Chicago Bulls,PF,5/22/97,5300400\nKris Dunn,Chicago Bulls,PG,3/18/94,5348007\nReggie Bullock,New York Knicks,SF,3/16/91,4000000\nMike Conley,Utah Jazz,PG,10/11/87,32511623\nJaylen Nowell,Minnesota Timberwolves,SG,7/9/99,1400000\nGorgui Dieng,Minnesota Timberwolves,C,1/18/90,16229213\nPatrick Patterson,Los Angeles Clippers,PF,3/14/89,3068660\nJarrett Allen,Brooklyn Nets,C,4/21/98,2376840\nBobby Portis,New York Knicks,C,2/10/95,15000000\nJoel Embiid,Philadelphia 76ers,C,3/16/94,27504630\nJonas Valanciunas,Memphis Grizzlies,C,5/6/92,16000000\nChris Chiozza,Washington Wizards,PG,11/21/95,79568\nKent Bazemore,Portland Trail Blazers,SF,7/1/89,19269663\nTristan Thompson,Cleveland Cavaliers,C,3/13/91,18539130\nMason Plumlee,Denver Nuggets,C,3/5/90,14041096\nShabazz Napier,Minnesota Timberwolves,PG,7/14/91,1845301\nEdmond Sumner,Indiana Pacers,PG,12/31/95,2000000\nAlex Len,Atlanta Hawks,C,6/16/93,4160000\nJosh Richardson,Philadelphia 76ers,SF,9/15/93,10116576\nBojan Bogdanovic,Utah Jazz,SF,4/18/89,17000000\nIman Shumpert,Brooklyn Nets,PG,6/26/90,2031676\nDaryl Macon,Miami Heat,SG,11/29/95,79568\nRodney McGruder,Los Angeles Clippers,SG,7/29/91,4807693\nBam Adebayo,Miami Heat,C,7/18/97,3454080\nJacob Evans,Golden State Warriors,SG,6/18/97,1928280\nNigel Williams-Goss,Utah Jazz,PG,9/16/94,1500000\nTerrance Ferguson,Oklahoma City Thunder,SF,5/17/98,2475840\nMichael Carter-Williams,Orlando Magic,PG,10/10/91,2028594\nBol Bol,Denver Nuggets,C,11/16/99,79568\nWillie Cauley-Stein,Golden State Warriors,C,8/18/93,2177483\nNikola Vucevic,Orlando Magic,C,10/24/90,28000000\nNicolas Batum,Charlotte Hornets,SF,12/14/88,25565217\nKyrie Irving,Brooklyn Nets,PG,3/23/92,31742000\nJeremy Lamb,Indiana Pacers,SF,5/30/92,10500000\nDonovan Mitchell,Utah Jazz,SG,9/7/96,3635760\nThanasis Antetokounmpo,Milwaukee Bucks,SF,7/18/92,1445697\nJames Johnson,Miami Heat,PF,2/20/87,15349400\nMonte Morris,Denver Nuggets,PG,6/27/95,1588231\nTerry Rozier,Charlotte Hornets,PG,3/17/94,19894737\nDeAndre Jordan,Brooklyn Nets,C,7/21/88,9881598\nJae Crowder,Memphis Grizzlies,SF,7/6/90,7815533\nJosh Gray,New Orleans Pelicans,PG,9/9/93,79568\nGoga Bitadze,Indiana Pacers,C,7/20/99,2816760\nKobi Simmons,Charlotte Hornets,PG,7/4/97,79568\nDerrick Favors,New Orleans Pelicans,C,7/15/91,17650000\nLandry Shamet,Los Angeles Clippers,SG,3/13/97,1995120\nJalen McDaniels,Charlotte Hornets,PF,1/31/98,898310\nBruno Caboclo,Memphis Grizzlies,SF,9/21/95,1845301\nDrew Eubanks,San Antonio Spurs,PF,2/1/97,79568\nRaul Neto,Philadelphia

In [45]:
myfile.close()

In [46]:
data = pd.read_csv('nba.csv')

In [48]:
data.head()

             Name                Team Position Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG  9/26/96  1445697
1  Christian Wood     Detroit Pistons       PF  9/27/95  1645357
2   PJ Washington   Charlotte Hornets       PF  8/23/98  3831840
3    Derrick Rose     Detroit Pistons       PG  10/4/88  7317074
4   Marial Shayok  Philadelphia 76ers        G  7/26/95    79568

In [49]:
for line in open('nba.csv'):
    print(line)

Name,Team,Position,Birthday,Salary

Shake Milton,Philadelphia 76ers,SG,9/26/96,1445697

Christian Wood,Detroit Pistons,PF,9/27/95,1645357

PJ Washington,Charlotte Hornets,PF,8/23/98,3831840

Derrick Rose,Detroit Pistons,PG,10/4/88,7317074

Marial Shayok,Philadelphia 76ers,G,7/26/95,79568

Draymond Green,Golden State Warriors,PF,3/4/90,18539130

Kendrick Nunn,Miami Heat,SG,8/3/95,1416852

Cedi Osman,Cleveland Cavaliers,SF,4/8/95,2907143

Brook Lopez,Milwaukee Bucks,C,4/1/88,12093024

Torrey Craig,Denver Nuggets,SF,12/19/90,2000000

Jordan Clarkson,Cleveland Cavaliers,PG,6/7/92,13437500

Alex Caruso,Los Angeles Lakers,PG,2/28/94,2750000

Norvel Pelle,Philadelphia 76ers,FC,2/3/93,79568

Tyler Johnson,Phoenix Suns,PG,5/7/92,19245370

Alec Burks,Golden State Warriors,SG,7/20/91,2320044

JaMychal Green,Los Angeles Clippers,PF,6/21/90,4767000

Dwight Howard,Los Angeles Lakers,C,12/8/85,5603850

Nikola Jokic,Denver Nuggets,C,2/19/95,27504630

Chris Boucher,Toronto Raptors,PF,1/11/93,1588231

Marcus Morris,New York Knicks,PF,9/2/89,15000000

Kevin Huerter,Atlanta Hawks,SG,8/27/98,2636280

Rui Hachimura,Washington Wizards,PF,2/8/98,4469160

George Hill,Milwaukee Bucks,PG,5/4/86,10133907

Nickeil Alexander-Walker,New Orleans Pelicans,SG,9/2/98,2964840

Jaylen Hoard,Portland Trail Blazers,SF,3/30/99,79568

Tyler Cook,Cleveland Cavaliers,PF,9/23/97,79568

Otto Porter,Chicago Bulls,SF,6/3/93,27250576

Langston Galloway,Detroit Pistons,PG,12/9/91,7333333

Evan Turner,Atlanta Hawks,PG,10/27/88,18606556

Norman Powell,Toronto Raptors,SG,5/25/93,10116576

Nicolas Claxton,Brooklyn Nets,PF,4/17/99,898310

Michael Frazier,Houston Rockets,G,3/8/94,79568

Paul Millsap,Denver Nuggets,PF,2/10/85,30000000

Furkan Korkmaz,Philadelphia 76ers,SG,7/24/97,1620564

Trey Burke,Philadelphia 76ers,PG,11/12/92,2028594

Bradley Beal,Washington Wizards,SG,6/28/93,27093018

Thomas Bryant,Washington Wizards,C,7/31/97,8000000

Dean Wade,Cleveland Cavaliers,PF,11/20/96,79568

Chris Paul,Oklahoma City Thunder,PG,5/6/85,38506482

Josh Hart,New Orleans Pelicans,SF,3/6/95,1934160

LaMarcus Aldridge,San Antonio Spurs,C,7/19/85,26000000

DaQuan Jeffries,Sacramento Kings,SG,8/30/97,898310

Hamidou Diallo,Oklahoma City Thunder,SF,7/31/98,1416852

Jamal Murray,Denver Nuggets,PG,2/23/97,4444746

Darius Bazley,Oklahoma City Thunder,PF,6/12/00,2284800

Robert Franks,Charlotte Hornets,F,12/18/96,79568

Gerald Green,Houston Rockets,SF,1/26/86,2564753

Thaddeus Young,Chicago Bulls,PF,6/21/88,12900000

Sviatoslav Mykhailiuk,Detroit Pistons,SF,6/10/97,1416852

Ian Mahinmi,Washington Wizards,C,11/5/86,15450051

Deonte Burton,Oklahoma City Thunder,SG,1/31/94,1416852

Markelle Fultz,Orlando Magic,PG,5/29/98,9745200

Aaron Gordon,Orlando Magic,PF,9/16/95,19863636

Dzanan Musa,Brooklyn Nets,SF,5/8/99,1911600

Patrick McCaw,Toronto Raptors,SF,10/25/95,4000000

Bismack Biyombo,Charlotte Hornets,C,8/28/92,17000000

JaVale McGee,Los Angeles Lakers,C,1/19/88,4000000

Juwan Morgan,Utah Jazz,F,4/17/97,796806

Marc Gasol,Toronto Raptors,C,1/29/85,25595700

Marcus Smart,Boston Celtics,PG,3/6/94,12553571

Rudy Gobert,Utah Jazz,C,6/26/92,24258427

Wesley Iwundu,Orlando Magic,SF,12/20/94,1618520

Dwight Powell,Dallas Mavericks,C,7/20/91,10259375

Goran Dragic,Miami Heat,PG,5/6/86,19217900

Theo Pinson,Brooklyn Nets,SG,11/5/95,1445697

Danilo Gallinari,Oklahoma City Thunder,PF,8/8/88,22615559

Joe Ingles,Utah Jazz,PF,10/2/87,11454546

Jarrett Culver,Minnesota Timberwolves,SG,2/20/99,5813640

Robert Covington,Minnesota Timberwolves,PF,12/14/90,11301219

Damyean Dotson,New York Knicks,SG,5/6/94,1618520

Patrick Beverley,Los Angeles Clippers,PG,7/12/88,12345680

Kevin Love,Cleveland Cavaliers,C,9/7/88,28942830

Quinn Cook,Los Angeles Lakers,PG,3/23/93,3000000

Justin Wright-Foreman,Utah Jazz,G,10/27/97,79568

Noah Vonleh,Minnesota Timberwolves,C,8/24/95,2000000

Tyus Jones,Memphis Grizzlies,PG,5/10/96,9258000

Dewayne Dedmon,Sacramento Kings,C,8/12/89,13333334

Malcolm Brogdon,Indiana Pacers,PG,12/11/92,20000000

Ben McLemore,Houston Rockets,SG,2/11/93,2028594

Wilson Chandler,Brooklyn Nets,PF,5/10/87,2564753

Isaac Bonga,Washington Wizards,PG,11/8/99,1416852

Adam Mokoka,Chicago Bulls,G,7/18/98,79568

Lonzo Ball,New Orleans Pelicans,PG,10/27/97,8719320

Jalen Brunson,Dallas Mavericks,PG,8/31/96,1416852

John Collins,Atlanta Hawks,PF,9/23/97,2686560

Marvin Williams,Charlotte Hornets,PF,6/19/86,15006250

Brad Wanamaker,Boston Celtics,PG,7/25/89,1445697

Donte DiVincenzo,Milwaukee Bucks,SG,1/31/97,2905800

Omari Spellman,Golden State Warriors,PF,7/21/97,1897800

Joe Harris,Brooklyn Nets,SF,9/6/91,7666667

Royce O'Neale,Utah Jazz,PF,6/5/93,1618520

Deandre Ayton,Phoenix Suns,C,7/23/98,9562920

Cory Joseph,Sacramento Kings,PG,8/20/91,12000000

Malcolm Miller,Toronto Raptors,SF,3/6/93,1588231

Justise Winslow,Miami Heat,PF,3/26/96,13000000

Kevin Durant,Brooklyn Nets,PF,9/29/88,37199000

Evan Fournier,Orlando Magic,SF,10/29/92,17000000

Chris Silva,Miami Heat,PF,9/19/96,79568

Vince Carter,Atlanta Hawks,PF,1/26/77,2564753

Cody Zeller,Charlotte Hornets,C,10/5/92,14471910

Brian Bowen,Indiana Pacers,SG,10/2/98,79568

Aaron Holiday,Indiana Pacers,PG,9/30/96,2239200

Troy Daniels,Los Angeles Lakers,SG,7/15/91,2028594

Buddy Hield,Sacramento Kings,SG,12/17/92,4861207

Terance Mann,Los Angeles Clippers,SG,10/18/96,1000000

John Konchar,Memphis Grizzlies,SG,3/22/96,79568

KZ Okpala,Miami Heat,SF,4/28/99,898310

Denzel Valentine,Chicago Bulls,SF,11/16/93,3377568

Marquese Chriss,Golden State Warriors,PF,7/2/97,1678854

Anthony Davis,Los Angeles Lakers,C,3/11/93,27093019

Nemanja Bjelica,Sacramento Kings,PF,5/9/88,6825000

Chandler Parsons,Atlanta Hawks,SF,10/25/88,25102512

Courtney Lee,Dallas Mavericks,SG,10/3/85,12759670

Myles Turner,Indiana Pacers,C,3/24/96,18000000

Kyle O'Quinn,Philadelphia 76ers,C,3/26/90,2174318

Bryn Forbes,San Antonio Spurs,SG,7/23/93,2875000

Duncan Robinson,Miami Heat,PF,4/22/94,1416852

Devin Booker,Phoenix Suns,SG,10/30/96,27285000

Grant Williams,Boston Celtics,PF,11/30/98,2379840

DeMarcus Cousins,Los Angeles Lakers,C,8/13/90,3500000

DeMar DeRozan,San Antonio Spurs,SF,8/7/89,27739975

Kristaps Porzingis,Dallas Mavericks,PF,8/2/95,27285000

Brandon Knight,Cleveland Cavaliers,PG,12/2/91,15643750

Thabo Sefolosha,Houston Rockets,PF,5/2/84,2564753

David Nwaba,Brooklyn Nets,SF,1/14/93,1678854

Quinndary Weatherspoon,San Antonio Spurs,G,9/10/96,79568

Dewan Hernandez,Toronto Raptors,C,12/9/96,898310

Isaiah Thomas,Washington Wizards,PG,2/7/89,2320044

Bruce Brown,Detroit Pistons,SG,8/15/96,1416852

Keldon Johnson,San Antonio Spurs,SF,10/11/99,1950600

Damian Jones,Atlanta Hawks,C,6/30/95,2305057

Luguentz Dort,Oklahoma City Thunder,G,4/19/99,79568

Terence Davis,Toronto Raptors,SG,5/16/97,898310

Chandler Hutchison,Chicago Bulls,SF,4/26/96,2332320

Steven Adams,Oklahoma City Thunder,C,7/20/93,25842697

Jordan Poole,Golden State Warriors,SG,6/19/99,1964760

Sekou Doumbouya,Detroit Pistons,SF,12/23/00,3285120

Zion Williamson,New Orleans Pelicans,F,7/6/00,9757440

Mike Muscala,Oklahoma City Thunder,C,7/1/91,2028594

Skal Labissiere,Portland Trail Blazers,C,3/18/96,2338846

Meyers Leonard,Miami Heat,C,2/27/92,11286515

Reggie Jackson,Detroit Pistons,PG,4/16/90,18086956

Alfonzo McKinnie,Cleveland Cavaliers,SF,9/17/92,1588231

Yuta Watanabe,Memphis Grizzlies,SF,10/13/94,79568

Kentavious Caldwell-Pope,Los Angeles Lakers,SG,2/18/93,8089282

Kelan Martin,Minnesota Timberwolves,SF,8/3/95,79568

OG Anunoby,Toronto Raptors,SF,7/17/97,2281800

Tyler Herro,Miami Heat,SG,1/20/00,3640200

Richaun Holmes,Sacramento Kings,C,10/15/93,4767000

Tyson Chandler,Houston Rockets,C,10/2/82,2564753

Solomon Hill,Memphis Grizzlies,SF,3/18/91,13290395

Keita Bates-Diop,Minnesota Timberwolves,SF,1/23/96,1416852

Kelly Olynyk,Miami Heat,C,4/19/91,12667885

Jaxson Hayes,New Orleans Pelicans,C,5/23/00,4862040

CJ McCollum,Portland Trail Blazers,SG,9/19/91,27556959

Darius Miller,New Orleans Pelicans,SF,3/21/90,7250000

Luka Doncic,Dallas Mavericks,PG,2/28/99,7683360

DeMarre Carroll,San Antonio Spurs,PF,7/27/86,7000000

Cristiano Felicio,Chicago Bulls,C,7/7/92,8156500

Zach LaVine,Chicago Bulls,PG,3/10/95,19500000

Tremont Waters,Boston Celtics,PG,1/10/98,79568

Dejounte Murray,San Antonio Spurs,PG,9/19/96,2321735

Jerome Robinson,Los Angeles Clippers,SG,2/22/97,3567720

Rudy Gay,San Antonio Spurs,PF,8/17/86,14500000

Ryan Broekhoff,Dallas Mavericks,SG,8/23/90,1416852

Jake Layman,Minnesota Timberwolves,PF,3/7/94,3581986

Cameron Johnson,Phoenix Suns,PF,3/3/96,4033440

Allen Crabbe,Atlanta Hawks,SG,4/9/92,18500000

Justin James,Sacramento Kings,SG,1/24/97,898310

Emmanuel Mudiay,Utah Jazz,PG,3/5/96,1737145

Avery Bradley,Los Angeles Lakers,PG,11/26/90,6767000

Victor Oladipo,Indiana Pacers,PG,5/4/92,21000000

Caleb Martin,Charlotte Hornets,SF,9/28/95,898310

Coby White,Chicago Bulls,SG,2/16/00,5307120

Isaiah Hartenstein,Houston Rockets,C,5/5/98,1416852

Will Barton,Denver Nuggets,SF,1/6/91,12776786

Dwayne Bacon,Charlotte Hornets,SG,8/30/95,1618520

Harrison Barnes,Sacramento Kings,PF,5/30/92,24147727

Tim Frazier,Detroit Pistons,PG,11/1/90,1620564

Jimmy Butler,Miami Heat,SF,9/14/89,32742000

Gary Harris,Denver Nuggets,SG,9/14/94,17839286

Thon Maker,Detroit Pistons,C,2/25/97,3569643

Shai Gilgeous-Alexander,Oklahoma City Thunder,PG,7/12/98,3952920

Hassan Whiteside,Portland Trail Blazers,C,6/13/89,27093018

Karl-Anthony Towns,Minnesota Timberwolves,C,11/15/95,27285000

Ky Bowman,Golden State Warriors,PG,6/16/97,79568

Ben Simmons,Philadelphia 76ers,PG,7/20/96,8113929

Terrence Ross,Orlando Magic,SF,2/5/91,12500000

Jordan McLaughlin,Minnesota Timberwolves,PG,4/9/96,79568

Daniel Theis,Boston Celtics,C,4/4/92,5000000

Jonathan Isaac,Orlando Magic,PF,10/3/97,5806440

Cheick Diallo,Phoenix Suns,C,9/13/96,1678854

Serge Ibaka,Toronto Raptors,C,9/18/89,23271604

Amile Jefferson,Orlando Magic,PF,5/7/93,1339515

Cam Reddish,Atlanta Hawks,SF,9/1/99,4245720

De'Anthony Melton,Memphis Grizzlies,PG,5/28/98,1416852

Udonis Haslem,Miami Heat,C,6/9/80,2564753

Charlie Brown,Atlanta Hawks,SG,2/2/97,79568

Elie Okobo,Phoenix Suns,PG,10/23/97,1416852

Gordon Hayward,Boston Celtics,PF,3/23/90,32700690

Marco Belinelli,San Antonio Spurs,SF,3/25/86,5846154

Javonte Green,Boston Celtics,SF,7/23/93,898310

Rondae Hollis-Jefferson,Toronto Raptors,SF,1/3/95,2500000

Carmelo Anthony,Portland Trail Blazers,PF,5/29/84,2159029

Danny Green,Los Angeles Lakers,SG,6/22/87,14634147

Stephen Curry,Golden State Warriors,PG,3/14/88,40231758

Eric Paschall,Golden State Warriors,PF,11/4/96,898310

Daniel Gafford,Chicago Bulls,C,10/1/98,898310

Anfernee Simons,Portland Trail Blazers,SG,6/8/99,2149560

Frank Kaminsky,Phoenix Suns,C,4/4/93,4767000

Luke Kennard,Detroit Pistons,SG,6/24/96,3827160

Josh Okogie,Minnesota Timberwolves,SG,9/1/98,2530680

Rodney Hood,Portland Trail Blazers,SF,10/20/92,5718000

De'Andre Hunter,Atlanta Hawks,SF,12/2/97,7068360

Klay Thompson,Golden State Warriors,SG,2/8/90,32742000

Jrue Holiday,New Orleans Pelicans,PG,6/12/90,26131111

PJ Dozier,Denver Nuggets,PG,10/25/96,79568

Andre Drummond,Detroit Pistons,C,8/10/93,27093018

Jared Harper,Phoenix Suns,PG,9/14/97,79568

Russell Westbrook,Houston Rockets,PG,11/12/88,38506482

Tony Bradley,Utah Jazz,C,1/8/98,1962360

Oshae Brissett,Toronto Raptors,SF,6/20/98,79568

Gary Clark,Houston Rockets,PF,11/16/94,1416852

Pascal Siakam,Toronto Raptors,PF,4/2/94,2351838

Eric Bledsoe,Milwaukee Bucks,PG,12/9/89,15625000

Tomas Satoransky,Chicago Bulls,PG,10/30/91,10000000

Davis Bertans,Washington Wizards,PF,11/12/92,7000000

Amir Coffey,Los Angeles Clippers,G,6/17/97,79568

Ignas Brazdeikis,New York Knicks,SF,1/8/99,898310

Ivan Rabb,New York Knicks,PF,2/4/97,79568

Khris Middleton,Milwaukee Bucks,SF,8/12/91,30603448

Kevin Knox,New York Knicks,PF,8/11/99,4380120

Jeff Green,Utah Jazz,PF,8/28/86,2564753

Ersan Ilyasova,Milwaukee Bucks,PF,5/15/87,7000000

Caleb Swanigan,Sacramento Kings,PF,4/18/97,2033160

Al Horford,Philadelphia 76ers,C,6/3/86,28000000

Clint Capela,Houston Rockets,C,5/18/94,16896552

Georges Niang,Utah Jazz,PF,6/17/93,1645357

Wesley Matthews,Milwaukee Bucks,SF,10/14/86,2564753

Rajon Rondo,Los Angeles Lakers,PG,2/22/86,2564753

Delon Wright,Dallas Mavericks,PG,4/26/92,9473684

Ja Morant,Memphis Grizzlies,PG,8/10/99,8730240

Fred VanVleet,Toronto Raptors,PG,2/25/94,9346153

Brandon Clarke,Memphis Grizzlies,PF,9/19/96,2478840

Miye Oni,Utah Jazz,SG,8/4/97,898310

Julius Randle,New York Knicks,C,11/29/94,18000000

Glenn Robinson III,Golden State Warriors,SF,1/8/94,1882867

Dillon Brooks,Memphis Grizzlies,SF,1/22/96,1618520

Zylan Cheatham,New Orleans Pelicans,SF,11/17/95,79568

Markieff Morris,Detroit Pistons,PF,9/2/89,3200000

Malik Beasley,Denver Nuggets,SG,11/26/96,2731713

John Wall,Washington Wizards,PG,9/6/90,38199000

Vlatko Cancar,Denver Nuggets,SF,4/10/97,898310

Alize Johnson,Indiana Pacers,PF,4/22/96,1416852

Andrew Wiggins,Minnesota Timberwolves,SF,2/23/95,27504630

Khyri Thomas,Detroit Pistons,SG,5/8/96,1416852

Mitchell Robinson,New York Knicks,C,4/1/98,1559712

Damian Lillard,Portland Trail Blazers,PG,7/15/90,29802321

Nassir Little,Portland Trail Blazers,PF,2/11/00,2105520

Mikal Bridges,Phoenix Suns,SF,8/30/96,4161000

Kyle Anderson,Memphis Grizzlies,PF,9/20/93,9073050

Garrett Temple,Brooklyn Nets,PG,5/8/86,4767000

Kyle Korver,Milwaukee Bucks,PF,3/17/81,6004753

Al-Farouq Aminu,Orlando Magic,PF,9/21/90,9258000

James Harden,Houston Rockets,PG,8/26/89,38199000

Derrick White,San Antonio Spurs,PG,7/2/94,1948080

JaKarr Sampson,Indiana Pacers,SF,3/20/93,1737145

Dario Saric,Phoenix Suns,PF,4/8/94,3481985

Ivica Zubac,Los Angeles Clippers,C,3/18/97,6481482

Juan Hernangomez,Denver Nuggets,PF,9/28/95,3321029

Jarrell Brantley,Utah Jazz,PF,6/7/96,79568

Eric Gordon,Houston Rockets,PG,12/25/88,14057730

Naz Reid,Minnesota Timberwolves,F,8/26/99,898310

Justin Robinson,Washington Wizards,PG,10/12/97,898310

Grayson Allen,Memphis Grizzlies,SG,10/8/95,2429400

Trevor Ariza,Sacramento Kings,SF,6/30/85,12200000

Brandon Goodwin,Atlanta Hawks,PG,10/2/95,79568

E'Twaun Moore,New Orleans Pelicans,PG,2/25/89,8664928

Mario Hezonja,Portland Trail Blazers,PF,2/25/95,1737145

Henry Ellenson,Brooklyn Nets,PF,1/13/97,79568

Johnathan Motley,Los Angeles Clippers,PF,5/4/95,79568

James Ennis,Philadelphia 76ers,SF,7/1/90,1882867

Andre Roberson,Oklahoma City Thunder,SF,12/4/91,10740740

Garrison Mathews,Washington Wizards,SG,10/24/96,79568

Jahlil Okafor,New Orleans Pelicans,C,12/15/95,1702486

Mfiondu Kabengele,Los Angeles Clippers,C,8/14/97,1977000

Treveon Graham,Minnesota Timberwolves,SG,10/28/93,1645357

Seth Curry,Dallas Mavericks,PG,8/23/90,7461380

D'Angelo Russell,Golden State Warriors,PG,2/23/96,27285000

Justin Holiday,Indiana Pacers,SG,4/5/89,4767000

Tyrone Wallace,Atlanta Hawks,PG,6/10/94,1620564

Miles Bridges,Charlotte Hornets,SF,3/21/98,3755400

Bogdan Bogdanovic,Sacramento Kings,SG,8/18/92,8529386

Matt Thomas,Toronto Raptors,SG,8/4/94,898310

Jordan Bell,Minnesota Timberwolves,C,1/7/95,1620564

Wenyen Gabriel,Sacramento Kings,PF,3/26/97,79568

Tony Snell,Detroit Pistons,SF,11/10/91,11392857

Shaquille Harrison,Chicago Bulls,PG,10/6/93,1620564

Yogi Ferrell,Sacramento Kings,PG,5/9/93,3150000

Mike Scott,Philadelphia 76ers,PF,7/16/88,4767000

Jarred Vanderbilt,Denver Nuggets,PF,4/3/99,1416852

Jeff Teague,Minnesota Timberwolves,PG,6/10/88,19000000

Zach Norvell,Los Angeles Lakers,SG,12/9/97,79568

Maxi Kleber,Dallas Mavericks,C,1/29/92,8000000

Matisse Thybulle,Philadelphia 76ers,SG,3/4/97,2582160

Ryan Arcidiacono,Chicago Bulls,PG,3/26/94,3000000

Wayne Ellington,New York Knicks,SG,11/29/87,8000000

Kawhi Leonard,Los Angeles Clippers,SF,6/29/91,32742000

Montrezl Harrell,Los Angeles Clippers,C,1/26/94,6000000

Jusuf Nurkic,Portland Trail Blazers,C,8/23/94,12000000

Matthew Dellavedova,Cleveland Cavaliers,PG,9/8/90,9607500

Cody Martin,Charlotte Hornets,SF,9/28/95,1173310

Zhaire Smith,Philadelphia 76ers,SG,6/4/99,3058800

RJ Barrett,New York Knicks,SG,6/14/00,7839960

Lonnie Walker,San Antonio Spurs,SG,12/14/98,2764200

Taurean Prince,Brooklyn Nets,SF,3/22/94,3481985

Elfrid Payton,New York Knicks,PG,2/22/94,8000000

Blake Griffin,Detroit Pistons,PF,3/16/89,34449964

Marko Guduric,Memphis Grizzlies,SG,3/8/95,2625000

Zach Collins,Portland Trail Blazers,C,11/19/97,4240200

Stanley Johnson,Toronto Raptors,PF,5/29/96,3623000

Boban Marjanovic,Dallas Mavericks,C,8/15/88,3500000

Josh Magette,Orlando Magic,PG,11/28/89,79568

Kyle Lowry,Toronto Raptors,PG,3/25/86,33296296

Darius Garland,Cleveland Cavaliers,PG,1/26/00,6400920

Frank Jackson,New Orleans Pelicans,PG,5/4/98,1618520

Dragan Bender,Milwaukee Bucks,PF,11/17/97,1678854

Kenrich Williams,New Orleans Pelicans,PF,12/2/94,1416852

Jerami Grant,Denver Nuggets,PF,3/12/94,9346153

Allonzo Trier,New York Knicks,PG,1/17/96,3551100

Pat Connaughton,Milwaukee Bucks,SG,1/6/93,1723050

Domantas Sabonis,Indiana Pacers,C,5/3/96,3529554

Dylan Windler,Cleveland Cavaliers,GF,9/22/96,2035800

Antonius Cleveland,Dallas Mavericks,SG,2/2/94,79568

Damion Lee,Golden State Warriors,SG,10/21/92,79568

Khem Birch,Orlando Magic,C,9/28/92,3000000

Aron Baynes,Phoenix Suns,C,12/9/86,5453280

Kemba Walker,Boston Celtics,PG,5/8/90,32742000

Nerlens Noel,Oklahoma City Thunder,C,4/10/94,1882867

Jabari Parker,Atlanta Hawks,PF,3/15/95,6500000

Carsen Edwards,Boston Celtics,SG,3/12/98,1228026

Anthony Tolliver,Portland Trail Blazers,PF,6/1/85,2564753

Lauri Markkanen,Chicago Bulls,PF,5/22/97,5300400

Kris Dunn,Chicago Bulls,PG,3/18/94,5348007

Reggie Bullock,New York Knicks,SF,3/16/91,4000000

Mike Conley,Utah Jazz,PG,10/11/87,32511623

Jaylen Nowell,Minnesota Timberwolves,SG,7/9/99,1400000

Gorgui Dieng,Minnesota Timberwolves,C,1/18/90,16229213

Patrick Patterson,Los Angeles Clippers,PF,3/14/89,3068660

Jarrett Allen,Brooklyn Nets,C,4/21/98,2376840

Bobby Portis,New York Knicks,C,2/10/95,15000000

Joel Embiid,Philadelphia 76ers,C,3/16/94,27504630

Jonas Valanciunas,Memphis Grizzlies,C,5/6/92,16000000

Chris Chiozza,Washington Wizards,PG,11/21/95,79568

Kent Bazemore,Portland Trail Blazers,SF,7/1/89,19269663

Tristan Thompson,Cleveland Cavaliers,C,3/13/91,18539130

Mason Plumlee,Denver Nuggets,C,3/5/90,14041096

Shabazz Napier,Minnesota Timberwolves,PG,7/14/91,1845301

Edmond Sumner,Indiana Pacers,PG,12/31/95,2000000

Alex Len,Atlanta Hawks,C,6/16/93,4160000

Josh Richardson,Philadelphia 76ers,SF,9/15/93,10116576

Bojan Bogdanovic,Utah Jazz,SF,4/18/89,17000000

Iman Shumpert,Brooklyn Nets,PG,6/26/90,2031676

Daryl Macon,Miami Heat,SG,11/29/95,79568

Rodney McGruder,Los Angeles Clippers,SG,7/29/91,4807693

Bam Adebayo,Miami Heat,C,7/18/97,3454080

Jacob Evans,Golden State Warriors,SG,6/18/97,1928280

Nigel Williams-Goss,Utah Jazz,PG,9/16/94,1500000

Terrance Ferguson,Oklahoma City Thunder,SF,5/17/98,2475840

Michael Carter-Williams,Orlando Magic,PG,10/10/91,2028594

Bol Bol,Denver Nuggets,C,11/16/99,79568

Willie Cauley-Stein,Golden State Warriors,C,8/18/93,2177483

Nikola Vucevic,Orlando Magic,C,10/24/90,28000000

Nicolas Batum,Charlotte Hornets,SF,12/14/88,25565217

Kyrie Irving,Brooklyn Nets,PG,3/23/92,31742000

Jeremy Lamb,Indiana Pacers,SF,5/30/92,10500000

Donovan Mitchell,Utah Jazz,SG,9/7/96,3635760

Thanasis Antetokounmpo,Milwaukee Bucks,SF,7/18/92,1445697

James Johnson,Miami Heat,PF,2/20/87,15349400

Monte Morris,Denver Nuggets,PG,6/27/95,1588231

Terry Rozier,Charlotte Hornets,PG,3/17/94,19894737

DeAndre Jordan,Brooklyn Nets,C,7/21/88,9881598

Jae Crowder,Memphis Grizzlies,SF,7/6/90,7815533

Josh Gray,New Orleans Pelicans,PG,9/9/93,79568

Goga Bitadze,Indiana Pacers,C,7/20/99,2816760

Kobi Simmons,Charlotte Hornets,PG,7/4/97,79568

Derrick Favors,New Orleans Pelicans,C,7/15/91,17650000

Landry Shamet,Los Angeles Clippers,SG,3/13/97,1995120

Jalen McDaniels,Charlotte Hornets,PF,1/31/98,898310

Bruno Caboclo,Memphis Grizzlies,SF,9/21/95,1845301

Drew Eubanks,San Antonio Spurs,PF,2/1/97,79568

Raul Neto,Philadelphia 76ers,PG,5/19/92,1737145

Jalen Lecque,Phoenix Suns,G,6/13/00,898310

Giannis Antetokounmpo,Milwaukee Bucks,PF,12/6/94,25842697

Malik Monk,Charlotte Hornets,SG,2/4/98,4028400

Tacko Fall,Boston Celtics,C,12/10/95,79568

Justin Jackson,Dallas Mavericks,PF,3/28/95,3280920

Paul George,Los Angeles Clippers,SF,5/2/90,33005556

Jayson Tatum,Boston Celtics,PF,3/3/98,7830000

Admiral Schofield,Washington Wizards,SF,3/30/97,1000000

Louis King,Detroit Pistons,F,4/6/99,79568

Kostas Antetokounmpo,Los Angeles Lakers,PF,11/20/97,79568

Rodions Kurucs,Brooklyn Nets,PF,2/5/98,1699236

Spencer Dinwiddie,Brooklyn Nets,PG,4/6/93,10605600

Doug McDermott,Indiana Pacers,PF,1/3/92,7333333

Romeo Langford,Boston Celtics,SG,10/25/99,3458400

Caris LeVert,Brooklyn Nets,SF,8/25/94,2625717

Michael Kidd-Gilchrist,Charlotte Hornets,PF,9/26/93,13000000

LeBron James,Los Angeles Lakers,PF,12/30/84,37436858

Taj Gibson,New York Knicks,C,6/24/85,9000000

Ty Jerome,Phoenix Suns,G,7/8/97,2193480

Chris Clemons,Houston Rockets,SG,7/23/97,79568

Luke Kornet,Chicago Bulls,C,7/15/95,2250000

Trey Lyles,San Antonio Spurs,PF,11/5/95,5500000

Sterling Brown,Milwaukee Bucks,SF,2/10/95,1618520

Andre Iguodala,Memphis Grizzlies,SF,1/28/84,17185185

Vincent Poirier,Boston Celtics,C,10/17/93,2505793

Frank Ntilikina,New York Knicks,PG,7/28/98,4855800

Jordan McRae,Washington Wizards,PG,3/28/91,1645357

Enes Kanter,Boston Celtics,C,5/20/92,4767000

John Henson,Cleveland Cavaliers,C,12/28/90,9732396

Jaylen Brown,Boston Celtics,SF,10/24/96,6534829

Jonah Bolden,Philadelphia 76ers,PF,1/2/96,1698450

Chimezie Metu,San Antonio Spurs,PF,3/22/97,1416852

Tobias Harris,Philadelphia 76ers,PF,7/15/92,32742000

Semi Ojeleye,Boston Celtics,PF,12/5/94,1618520

Jevon Carter,Phoenix Suns,PG,9/14/95,1416852

Brandon Ingram,New Orleans Pelicans,PF,9/2/97,7265485

Moritz Wagner,Washington Wizards,C,4/26/97,2063520

Dorian Finney-Smith,Dallas Mavericks,PF,5/4/93,4000000

Danuel House,Houston Rockets,SF,6/7/93,3540000

Nicolo Melli,New Orleans Pelicans,C,1/26/91,4102564

Talen Horton-Tucker,Los Angeles Lakers,GF,11/25/00,898310

Ed Davis,Utah Jazz,C,6/5/89,4767000

Kyle Guy,Sacramento Kings,G,8/11/97,79568

Kadeem Allen,New York Knicks,PG,1/15/93,79568

Dante Exum,Utah Jazz,PG,7/13/95,9600000

Abdel Nader,Oklahoma City Thunder,SF,9/25/93,1618520

Bruno Fernando,Atlanta Hawks,C,8/15/98,1400000

Dion Waiters,Miami Heat,SG,12/10/91,12100000

Jared Dudley,Los Angeles Lakers,PF,7/10/85,2564753

Max Strus,Chicago Bulls,SG,3/28/96,79568

Kevon Looney,Golden State Warriors,C,2/6/96,4464286

Willy Hernangomez,Charlotte Hornets,C,5/27/94,1557250

Melvin Frazier,Orlando Magic,SG,8/30/96,1416852

Austin Rivers,Houston Rockets,PG,8/1/92,2174310

Harry Giles,Sacramento Kings,PF,4/22/98,2578800

Robin Lopez,Milwaukee Bucks,C,4/1/88,4767000

Collin Sexton,Cleveland Cavaliers,PG,1/4/99,4764960

Ricky Rubio,Phoenix Suns,PG,10/21/90,16200000