## Jupyter Notebook Cell Execution

In [1]:
1 + 1

2

In [2]:
2 + 2
3 + 3

6

## Import Pandas

In [3]:
import pandas as pd

pd.__version__

'2.2.2'

## Create Series Object

In [4]:
# Series - 1 dimensional data structure
#   
#  A  Pepsi
#  B  Coke
#  C  Dr. Pepper

# DataFrame - 2 dimensional data structure
#
#        1             2                   3
#  A  Pepsi        Diet Pepsi         Cherry Pepsi
#  B  Coke         Diet Coke          Cherry Coke
#  C  Dr. Pepper   Diet Dr. Pepper   Cherry Dr. Pepper

ice_cream_flavors = ["Chocolate", "Vanilla", "Strawberry", "Rum Raisin"]

pd.Series(ice_cream_flavors)

0     Chocolate
1       Vanilla
2    Strawberry
3    Rum Raisin
dtype: object

## Parameters and Arguments

In [5]:
pd.Series(data = ice_cream_flavors)

0     Chocolate
1       Vanilla
2    Strawberry
3    Rum Raisin
dtype: object

In [6]:
ice_cream_flavors = ["Chocolate", "Vanilla", "Strawberry", "Rum Raisin"]
day_of_week = ["Monday", "Wednesday", "Friday", "Saturday"]

pd.Series(ice_cream_flavors, day_of_week)

pd.Series(data = ice_cream_flavors, index = day_of_week)

Monday        Chocolate
Wednesday       Vanilla
Friday       Strawberry
Saturday     Rum Raisin
dtype: object

## Another Series Example

In [7]:
lucky_numbers = [4, 8, 15, 16, 23, 42]

pd.Series(lucky_numbers)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

## Importing CSV Dataset

In [14]:
pd.read_csv("pokemon.csv", index_col = "Pokemon")

                       Type
Pokemon
Bulbasaur    Grass / Poison
Ivysaur      Grass / Poison
Venusaur     Grass / Poison
Charmander             Fire
Charmeleon             Fire
...                     ...
Stakataka      Rock / Steel
Blacephalon    Fire / Ghost
Zeraora            Electric
Meltan                Steel
Melmetal              Steel

[809 rows x 1 columns]

In [16]:
pokemon = pd.read_csv("pokemon.csv", index_col = "Pokemon")
pokemon.head()

                      Type
Pokemon
Bulbasaur   Grass / Poison
Ivysaur     Grass / Poison
Venusaur    Grass / Poison
Charmander            Fire
Charmeleon            Fire

In [17]:
pokemon

                       Type
Pokemon
Bulbasaur    Grass / Poison
Ivysaur      Grass / Poison
Venusaur     Grass / Poison
Charmander             Fire
Charmeleon             Fire
...                     ...
Stakataka      Rock / Steel
Blacephalon    Fire / Ghost
Zeraora            Electric
Meltan                Steel
Melmetal              Steel

[809 rows x 1 columns]

## Previewing a Series

In [18]:
pokemon.head()
pokemon.head(6)

pokemon.head(1)
pokemon.head(n = 1)

                     Type
Pokemon
Bulbasaur  Grass / Poison

In [19]:
pokemon.tail()

pokemon.tail(8)

pokemon.tail(1)

           Type
Pokemon
Melmetal  Steel

## Sorting a Series by Values

In [29]:
pokemon.sort_values(["Type"])
pokemon.sort_values(["Type"],ascending = True)

                     Type
Pokemon
Illumise              Bug
Silcoon               Bug
Pinsir                Bug
Burmy                 Bug
Wurmple               Bug
...                   ...
Tirtouga     Water / Rock
Relicanth    Water / Rock
Corsola      Water / Rock
Carracosta   Water / Rock
Empoleon    Water / Steel

[809 rows x 1 columns]

In [28]:
pokemon.Type.sort_values(ascending = False)

Pokemon
Empoleon      Water / Steel
Corsola        Water / Rock
Relicanth      Water / Rock
Carracosta     Water / Rock
Tirtouga       Water / Rock
                  ...
Kricketune              Bug
Cascoon                 Bug
Scatterbug              Bug
Kricketot               Bug
Grubbin                 Bug
Name: Type, Length: 809, dtype: object

## Sorting a Series by Index

In [30]:
pokemon.head()

                      Type
Pokemon
Bulbasaur   Grass / Poison
Ivysaur     Grass / Poison
Venusaur    Grass / Poison
Charmander            Fire
Charmeleon            Fire

In [31]:
pokemon.sort_index()
pokemon.sort_index(ascending = True)

                      Type
Pokemon
Abomasnow      Grass / Ice
Abra               Psychic
Absol                 Dark
Accelgor               Bug
Aegislash    Steel / Ghost
...                    ...
Zoroark               Dark
Zorua                 Dark
Zubat      Poison / Flying
Zweilous     Dark / Dragon
Zygarde    Dragon / Ground

[809 rows x 1 columns]

In [32]:
pokemon.sort_index(ascending = False)

                      Type
Pokemon
Zygarde    Dragon / Ground
Zweilous     Dark / Dragon
Zubat      Poison / Flying
Zorua                 Dark
Zoroark               Dark
...                    ...
Aegislash    Steel / Ghost
Accelgor               Bug
Absol                 Dark
Abra               Psychic
Abomasnow      Grass / Ice

[809 rows x 1 columns]

## The `inplace` Parameter

In [35]:
pokemon.sort_values(["Type"], inplace = True)

In [36]:
pokemon.head()

         Type
Pokemon
Illumise  Bug
Silcoon   Bug
Pinsir    Bug
Burmy     Bug
Wurmple   Bug

In [37]:
pokemon.sort_index(inplace = True)

In [38]:
pokemon.head()

                    Type
Pokemon
Abomasnow    Grass / Ice
Abra             Psychic
Absol               Dark
Accelgor             Bug
Aegislash  Steel / Ghost

## The `value_counts` Method

In [39]:
pokemon.head()

                    Type
Pokemon
Abomasnow    Grass / Ice
Abra             Psychic
Absol               Dark
Accelgor             Bug
Aegislash  Steel / Ghost

In [40]:
pokemon.value_counts()
pokemon.value_counts(ascending = False)

Type
Normal              65
Water               61
Grass               38
Psychic             35
Fire                30
                    ..
Rock / Poison        1
Steel / Ground       1
Steel / Fighting     1
Steel / Dragon       1
Water / Steel        1
Name: count, Length: 159, dtype: int64

In [41]:
pokemon.value_counts(ascending = True)

Type
Bug / Ghost           1
Bug / Ground          1
Dragon / Electric     1
Dark / Ghost          1
Dragon / Fire         1
                     ..
Fire                 30
Psychic              35
Grass                38
Water                61
Normal               65
Name: count, Length: 159, dtype: int64

In [42]:
pokemon.value_counts(normalize = True) * 100

Type
Normal              8.034611
Water               7.540173
Grass               4.697157
Psychic             4.326329
Fire                3.708282
                      ...
Rock / Poison       0.123609
Steel / Ground      0.123609
Steel / Fighting    0.123609
Steel / Dragon      0.123609
Water / Steel       0.123609
Name: proportion, Length: 159, dtype: float64

## Uniqueness

In [43]:
pokemon.nunique()

Type    159
dtype: int64

In [48]:
pokemon.nunique(axis=0)

Type    159
dtype: int64

In [49]:
pokemon.drop_duplicates()

                        Type
Pokemon
Abomasnow        Grass / Ice
Abra                 Psychic
Absol                   Dark
Accelgor                 Bug
Aegislash      Steel / Ghost
...                      ...
Tyranitar        Rock / Dark
Tyrantrum      Rock / Dragon
Victini       Psychic / Fire
Volcanion       Fire / Water
Zekrom     Dragon / Electric

[159 rows x 1 columns]

In [50]:
pokemon.shape

(809, 1)

In [52]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 809 entries, Abomasnow to Zygarde
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Type    809 non-null    object
dtypes: object(1)
memory usage: 44.9+ KB

## Select Rows by Index Position

In [53]:
pokemon.head()

                    Type
Pokemon
Abomasnow    Grass / Ice
Abra             Psychic
Absol               Dark
Accelgor             Bug
Aegislash  Steel / Ghost

In [54]:
pokemon.iloc[0]

Type    Grass / Ice
Name: Abomasnow, dtype: object

In [55]:
pokemon.iloc[100]

Type    Grass / Fighting
Name: Chesnaught, dtype: object

In [32]:
# pokemon.iloc[10000]

In [56]:
pokemon.iloc[[0, 3, 5, 10]]

                       Type
Pokemon
Abomasnow       Grass / Ice
Accelgor                Bug
Aerodactyl    Rock / Flying
Altaria     Dragon / Flying

In [57]:
pokemon.iloc[101:104]

            Type
Pokemon
Chespin    Grass
Chikorita  Grass
Chimchar    Fire

In [58]:
pokemon.iloc[-10:-3]

                        Type
Pokemon
Zapdos     Electric / Flying
Zebstrika           Electric
Zekrom     Dragon / Electric
Zeraora             Electric
Zigzagoon             Normal
Zoroark                 Dark
Zorua                   Dark

In [59]:
pokemon.iloc[-8:]

                        Type
Pokemon
Zekrom     Dragon / Electric
Zeraora             Electric
Zigzagoon             Normal
Zoroark                 Dark
Zorua                   Dark
Zubat        Poison / Flying
Zweilous       Dark / Dragon
Zygarde      Dragon / Ground

In [60]:
pokemon.iloc[:4]

                  Type
Pokemon
Abomasnow  Grass / Ice
Abra           Psychic
Absol             Dark
Accelgor           Bug

## Select Rows by Index Label

In [61]:
pokemon.head()

                    Type
Pokemon
Abomasnow    Grass / Ice
Abra             Psychic
Absol               Dark
Accelgor             Bug
Aegislash  Steel / Ghost

In [39]:
pokemon.loc["Pikachu"]

'Electric'

In [62]:
pokemon.loc["Charizard"]

Type    Fire / Flying
Name: Charizard, dtype: object

In [63]:
pokemon.loc[["Pikachu", "Mewtwo", "Dragonite"]]

                      Type
Pokemon
Pikachu           Electric
Mewtwo             Psychic
Dragonite  Dragon / Flying

In [42]:
# pokemon.loc["nonsense"]